### ISSUE TITLE
Stable version and changelog?

### ISSUE THREAD

**Issue by zhaoyao91** [remeda/remeda#103]
This lib has not released a minor version yet, so we have the risk of suffering a breaking change. Do you have a plan to release a minor/major version and record changes via changelog? [changesets](https://github.com/atlassian/changesets) is a great tool for this.

**Comment by TkDodo** [comment]
I would love to get changesets or something similar set up, but I'm lacking the experience to do so. For now, I've started writing manual release notes when releases are made, see the releases page: https://github.com/remeda/remeda/releases

regarding stable version: I honestly haven't seen us doing breaking changes in the last year or so, and I don't see why we would - the functions are pretty stable.

Unless I'm missing something, I think we could release the latest changes as v1. What do you think @lstkz ?

**Comment by vladimiry** [comment]
> I honestly haven't seen us doing breaking changes in the last year or so, and I don't see why we would - the functions are pretty stable.

No blaming of something, but it's not really so.

**Comment by TkDodo** [comment]
> No blaming of something, but it's not really so.

i guess i missed it then. Been using it for 2 years and no upgrade has shown any issues. 

> v0.0.29 is broken by the way.

a type issue for class usages isn’t exactly „broken“, but the fix is merged already and the question was more if it should become 0.0.30 or 1.0.0 :)

**Comment by vladimiry** [comment]
> i guess i missed it then. Been using it for 2 years and no upgrade has shown any issues.

I was not exactly correct since #107 and #138 were not caught by automated tests bugs but not explicitly introduced breaking changes.

> the question was more if it should become 0.0.30 or 1.0.0 :)

v1 looks fine for me as the functionality looks settled. Would appreciate the changelist (on releases page or individual markdown page, no difference).

**Comment by TkDodo** [comment]
Yes I think bugs can happen to the best of us. I was more referring to intentional breaking api changes :)

**Comment by TkDodo** [comment]
published as [0.0.30](https://github.com/remeda/remeda/releases/tag/v0.0.30) for now

**Comment by 0x80** [comment]
Not sure if it matters to many developers but to me, version 0.0.30 signals that the project is still in its infancy. There must have been many features added over the years so I would expect the version to be 0.30.0 instead.

From what I gather the project is quite mature, so maybe a 1.0 release could help adoption.

**Comment by Bessonov** [comment]
From my point of view, the version doesn't matter. It doesn't tell anything about maturity, features or about whatever. For example, nginx stuck around 10 years 0.x and, well, it was rock stable from day I used it (~2008). Not without bug, but in very professional hands of Igor, Maxim and co. Other projects rush to 1.0 and then change everything in 2.0, then again in 3.0 and still very unstable.

Said that, I have no stakes about versioning and sure that 1.0 would help people who look at x.y to decide... but I'm not sure that it's right point to do that yet.

**Comment by 0x80** [comment]
Yes of course a version string does not give any guarantees and can be used however you like, but semantic versioning is what most people expect and don't see the advantage to use it differently.

Sticking at a minor version like Nginx did is very common and makes a lot of sense within semantic versioning, because then you can still introduce breaking changes before you feel like you've reached 1.0.

But by only incrementing the patch/bug part of the semantic version, like was done in Remeda, a library consumer can never know how to interpret the new version. Because major+minor+bugfixes are all crammed into the same number. I don't see how that is helping anyone. 

With Nginx at least you could expect a change from 0.12 to 0.13 to break things, and assume that it would be fine to upgrade from 0.12.0 to 0.12.5.

**Comment by JeffBeltran** [comment]
When i first grok a tool, if it's not v1 i will typically skip over it unless the project i want it for is a hobby one. There are exceptions to this rule, axios, but even those annoys me. Most of our tooling leans into semver to keep a simple standards of

1. This update is gonna break stuff (major)
2. This update added new things (minor)
3. This update fixed a bug (patch)
4. This update could be any of the above or im still working on it (anything under v1 version)

IMO, Given the length of time this project has been active it's time to move it out of the "beta/alpha" stage and get it to SemVer so we can quickly know if/when we should be updating the package.

Here is a really good article that that does a much better job articulating this: https://blog.greenkeeper.io/introduction-to-semver-d272990c44f2

**Comment by vladimiry** [comment]
I'd prefer the package moves to v1+ versioning as when I run `yarn upgrade-interactive --latest` and see red items I would normally go to package's changelog and review the breaking changes. Currently that command highlights "remeda" updates in red more often than actually needed.

**Comment by JeffBeltran** [comment]
> I'd prefer the package moves to v1+ versioning as when I run yarn upgrade-interactive --latest and see red items I would normally go to package's changelog and review the breaking changes. 

Legit the same reason i posted this lol

**Comment by vlad-yakovlev** [comment]
Should be resolved in #185:
- stable version – ✅
- changelog - ✅ (in github releases)

**Comment by dartess** [comment]
It seems that this can also be closed? @TkDodo
