### ISSUE TITLE
Ramda types for prop and pluck are better than remeda ones

### ISSUE THREAD

**Issue by ellipticaldoor** [remeda/remeda#12]
I general I finding that remeda is better typed than ramda, but I found a case where is still better.

When making a curried pluck or map(prop) the remeda types system doesn't detects my intent

``` typescript
import { pluck } from "ramda";
import { map, prop } from "remeda";

const slugsArray = [{ slug: "a" }, { slug: "b" }];
const wrongSlugsArray = [{ wrongslug: "a" }, { wrongslug: "b" }];

// Argument of type '"slug"' is not assignable to parameter of type 'never'.
const plukSlugs = map(prop("slug"));

// Ramda works nice
const ramdaPlukSlugs = pluck("slug");

// This one works fine
const ramdaResult = ramdaPlukSlugs(slugsArray);

// Ramda complains wrongSlugsArray doesn't has the key that is expecting
const ramdaWrongResult = ramdaPlukSlugs(wrongSlugsArray);
// Property 'slug' is missing in type '{ wrongslug: string; }' but required in type 'Record<"slug", {}>'.
```

**Comment by BetterCallSky** [comment]
Higher-order functions don't work well in typescript.
If you do something like this in Ramda
```ts
const resultFn = fun1(fun2('args')) 
```
then you will also have problems with static typing or the input argument will be `any` or `{}` in `resultFn`.

Function composition should be created with [createPipe](https://remedajs.com/docs#createPipe).
Unfortunately, there is no better solution in TypeScript.

**Comment by ellipticaldoor** [comment]
How it would be?

Now Im doing this, but maybe there is a better alternative

```
interface Post {
  slug: String
}

const plukSlugs = (posts: Post[]) => map(prop("slug"));
```

**Comment by BetterCallSky** [comment]
This should work
```ts
const plukSlugs = (posts: Post[]) => R.map(posts, R.prop("slug"));
```

using `pipe`, or `createPipe` is useful if there are more functions/transformations.  

Native solutions are also ok for short transformations.
```ts
const plukSlugs = (posts: Post[]) =>  posts.map(x => x.slug);
```

**Comment by ellipticaldoor** [comment]
Thank you!
