### ISSUE TITLE
Include undefined in result of groupBy

### ISSUE THREAD

**Issue by Bessonov** [remeda/remeda#133]
Current typing

```typescript
export function groupBy<T>(
  items: readonly T[],
  fn: (item: T) => any
): Record<string, T[]>;
```

can lead to wrong assumption:

```typescript
// no error
const grouped = groupBy([{ a: 1 }], ({ a }) => a)['notExists'][0].a
```

Therefore I propose to change the result type to `Record<string, T[] | undefined>`. Be aware that it's a breaking change.

**Comment by TkDodo** [comment]
Every object index access suffers form this, and I think this can be solved by turning on the `noUncheckedIndexedAccess` compiler flag in TS 4.1: https://www.typescriptlang.org/tsconfig/#noUncheckedIndexedAccess

**Comment by Bessonov** [comment]
Oh, you're right! Thanks!
