### ISSUE TITLE
Am I doing something wrong when using Object.values?

### ISSUE THREAD

**Issue by rarenatoe** [remeda/remeda#136]
Currently there is no `values` remeda function, so instead I use `Object.values` when I need to get the values of an object without its keys, however this causes the resulting values from `Object.values` to be of type `any[]`.
If I pipe this, the entire chain of excellent inferred typing that remeda does is thrown out of the window.
Here is an example of what I am taking about:
<img width="895" alt="Screen Shot 2021-07-18 at 12 30 04" src="https://user-images.githubusercontent.com/44821537/126076876-46a797c4-272d-4ed5-9476-ee3848c979f0.png">

I have tried using `(o): (A | B | C)[] => Object.values(o)` but it ends up being just a confusing mess going down the chain.

Am I doing something wrong or should I start a feature request for a `values` function?

Useful information:
- I use target: "es5" in tsconfig and cannot change it since my target are web browsers.

**Comment by TkDodo** [comment]
it seems like the "wrong" overload of `Object.values` is chosen, from `lib.es2017.object.d.ts`:

```
    values<T>(o: { [s: string]: T } | ArrayLike<T>): T[];
    values(o: {}): any[];
```

not sure if we can do something about this, I tried the most minimal example:

```
const test = pipe(
    ['one', 'two', 'three'],
    Object.values
)
```

and `test` is `Array<any>` here, too. The types should flow through pipe, so I'm sure adding an `Object.values` as well as an `Object.keys` equivalent to remeda should work. Do you want to give it a try?

**Comment by rarenatoe** [comment]
I would love to.
How should I go about it? Is there a sort of guide? I've never contributed to something like this before.
