### ISSUE TITLE
"Index signature is missing in type ..."-like TS compilation error when the object is shaped by TS interface vs type

### ISSUE THREAD

**Issue by vladimiry** [remeda/remeda#138]
So it works when the object type is shaped using "type" but gets failed if it's shaped using "interface".

Broken since v0.0.29 by #134. CC @mechamobau

See https://github.com/microsoft/TypeScript/issues/15300 as related issue.

**Comment by TkDodo** [comment]
Do you have an example of remeda code that was working before that is not working now please?

**Comment by vladimiry** [comment]
The following code stops working since  0.0.29 unless you declare `ValueType` via `type` vs `interface`:

```typescript
import {omit} from "remeda";

interface ValueType {
    prop1: string
    prop2: number
}

export const letsOmitProp1 = (value: ValueType): Omit<ValueType, "prop1"> => {
    return omit(value, ["prop1"]);
};
```

**Comment by TkDodo** [comment]
not sure what to do against this, since it looks like a TypeScript issue. @mechamobau do you have any ideas?

**Comment by mechamobau** [comment]
@vladimiry @TkDodo 
I found the bug, the interfaces don't have implicitly index-type signatures, to solve that the `Record` needs to receive `any` as the value type declaration. [This example it's easier to see the problem](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGpwDYFcIBUCeADigN4BQylyhUA9oQIwBcyAzmFKAOYVU30AmFiCwBbAEbQyAXzJkA9POQB5DABNktUcDDIwRFK2BcQcMFigoAFAHcdAC2QlpASjlqICDHEvIYWEAQwYFoQTW0wAB5cZAgAD0gQNVYnaQAaZABpWISIJJSAawh8WhhkXAA+K15acQArTzAWXDTeU1EIVhZLODVQjHwsgG0AXTIXFmUI6IzMioBuOS0dKwByKDgkrTZzGBhVjKHVhFCEM1WRl2RFcvtgFPvkUAA3TGA1MmWwKxI-WloWKtxD5Vsh0sgjjB-hcrjdcHcHilXhh3mR4oRaFBdCcQOxkBgIGBWFMdAAFOiMZAAXmQVmROBY6GweAMExU0yZOAIxAyACJ+IxeRVqcLyFRkJZzFAwl86ZgcId+RSGLzLvNrkp4Y9HsjUdJFgpNQZkB4vD4zCFccg7GBHLaUOIsFxaTbHAAlTyYtSRcn0aD6TLFDIBAogWg2EAVCbuTzeXz+QLBULIAD6X2iOUSyWQHpOUG9vuIWPwgfwwZAofDkdmmby2aKJTKlWqlFqDSCzValHanW6EF6-UGmVG40m0xaWQWcjTETWGy2oh2WD2Bwhx1O50uGtu2oeIF1HxnK1+UIByCBILBh1Wp5h261iOQB7RcQxWOQOLxKYJRJJYELDDUrS9IQIy8ossQbJ-pEnIQRAfICiqwpUqKvCUJKFhhEe3wgYqiGqi46pwgiTxIm8Hz6nIcLGqacYWqEKQwMAcQQBotgODmnr5j6FL+iWQbIJs+BRkwMZmvGARBJaqbYRm8RZikuZejxfrFqWGRCRUNbyXWhTFKU5RVDU9SNJ2bRwB0XQSv2fQgAMwxjFB46zFOZApthc6bH0i7sMu+zXjiZxgHexG7k8+7kW5Hknv8gLAlAoLgpC0JbqFj7PuimLYgxujuT+xIRABQFysyYHMtyEBOToMHgRVCHKkKIpOGh1lSlhHm4RCSr0Cqar3iROqRfqQA).

I opened a PR that solves this issue

**Comment by TkDodo** [comment]
@mechamobau thank you for the quick response. I'll likely release later today
