### ISSUE TITLE
Is there a trace or log function available in Remeda

### ISSUE THREAD

**Issue by JackEdwardLyons** [remeda/remeda#151]
Just a quick question - is it possible to log or trace outputs/results when composing functions?

**Comment by Bessonov** [comment]
I think this would be an interesting feature for debugging. But how should it works in general way?

Maybe for a specific implementation we need something like rxjs' [tap](https://rxjs.dev/api/operators/tap). Probably you can simulate that by using `map` with `console.log`. WDYT?

**Comment by Bessonov** [comment]
Oh, there is a pr for tap: https://github.com/remeda/remeda/pull/149
