### ISSUE TITLE
capitalize and other string oriented functions?

### ISSUE THREAD

**Issue by jasonkuhrt** [remeda/remeda#162]
Are there plans to add string oriented functions like capitalize?

**Comment by jasonkuhrt** [comment]
Oh maybe not... https://github.com/remeda/remeda/issues/42

**Comment by jasonkuhrt** [comment]
Not sure why this library would hold back though, now I just end up using lodash and remeda in my project :)

**Comment by TkDodo** [comment]
as stated here, we want to focus on object/arrays for now and not strings:

- https://github.com/remeda/remeda/issues/207#issuecomment-1213081826
