### ISSUE TITLE
Bug in the docs for findIndex

### ISSUE THREAD

**Issue by woss** [remeda/remeda#166]
The examples in this part are wrong https://remedajs.com/docs#findIndex

This is in the docs: 
![image](https://user-images.githubusercontent.com/80440/161070869-4aa1e424-0794-4a9a-90a1-f2ebe0fb0b64.png)

This is what gets returned:
![image](https://user-images.githubusercontent.com/80440/161070601-60b34428-9907-43ee-900e-47dd950fc99c.png)

**Comment by TkDodo** [comment]
seems like a copy paste error. would you like to contribute a PR to update it? you'd only need to update the code comment, as the docs get generated from that.

**Comment by woss** [comment]
i'd love to, but then it will wait for 1 month. i am off to the airport to Croatia for the holidays :)
