### ISSUE TITLE
An example how to delete the item from an array

### ISSUE THREAD

**Issue by woss** [remeda/remeda#167]
i'm trying to get my head around this project coming from ramda. the title says it all :)  

Thing is that I know how to delete it via vanilla JS, but then again, i'd like to know how to do it with the remeda

**Comment by TkDodo** [comment]
I'd probably just use `filter` to do that?

**Comment by woss** [comment]
exactly that, but how?

 the filter accepts the function as a param and the data. i need to find specific value in the array and delete it.

**Comment by TkDodo** [comment]
```
const myArray = ['foo', 'bar']
const result = R.filter(myArray, (elem) => elem !== 'foo') // ['bar']
```

**Comment by woss** [comment]
uf, that's not going to happen :)  
I need this in a dynamic way. isn't there a way to `compose`  the functions then call it with the arg I need to delete?

**Comment by TkDodo** [comment]
I don't quite follow. can you maybe post an example of what you need?

```
const deleteItemFromArray = (array, item) => R.filter(array, (elem) => elem !== item)

deleteItemFromArray(['foo', 'bar'], 'foo')
```

of course you can also compose it differently:

```
const remove = (item: string) => R.filter((elem: string) => elem !== item)

remove('foo')(['foo', 'bar'])
```

**Comment by woss** [comment]
that is what i was looking for, thanks, now when you posted it, it looks so obvious, but then I got used to `compose` functions with ramda, I guess the change of mindset will be required :)
