### ISSUE TITLE
`R.last()` working incorrectly

### ISSUE THREAD

**Issue by nghiepit** [remeda/remeda#177]
Related https://github.com/remeda/remeda/issues/173

`R.last()` is implementing result like of `R.first()`
```ts
R.pipe(
  [1, 2, 4, 8, 16],
  R.filter((x) => x > 3),
  R.last(),
  (x) => x + 1
); // 17
```
But the actual result is 5 😢 

https://codesandbox.io/s/boring-hopper-gxtmd9?file=/src/index.ts

**Comment by TkDodo** [comment]
Thanks for reporing. It seems that the mistake is that `last` is not pipeable - it's just not implemented, like it is in `first`.

**Comment by DanielHall977** [comment]
I'll handle this.

**Comment by DanielHall977** [comment]
Fixed: https://github.com/remeda/remeda/pull/179
