### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by vlad-yakovlev** [remeda/remeda#185]
Requirements:
- uses github actions
- uses conventional commits
- the commit prefix (fix, feat) decides if major or minor release
- everything automated

Example: https://github.com/TanStack/query/blob/8a332bd05037497e12055a60dafd75b28daef317/.github/workflows/test-and-publish.yml#L41-L53

**Comment by TkDodo** [comment]
what I currently do to trigger a release is:

```
./scripts/build.sh 
npm version patch  
npm publish
```
