### ISSUE TITLE
toPairs does not work in pipe

### ISSUE THREAD

**Issue by 0x80** [remeda/remeda#19]
```ts
const obj = { foo: "bar" }
const result = R.pipe(obj, 
  R.toPairs(),
  ...
)
```

Typescript is complaining that toPairs requires an argument.

**Comment by BetterCallSky** [comment]
omit `()`

```ts
const obj = { foo: 'bar' };
const result = R.pipe(
  obj,
  R.toPairs
); // [ [ 'foo', 'bar' ] ]

```

**Comment by 0x80** [comment]
@BetterCallSky 	Hmm that sounds plausible :) But then please help me understand this example from the readme:

```ts
// Get first 3 unique values
const arr = [1, 2, 2, 3, 3, 4, 5, 6];

const result = R.pipe(
  arr,                    // only four iterations instead of eight (array.length)
  R.map(x => {
    console.log('iterate', x);
    return x;
  }),
  R.uniq(),
  R.take(3)
); // => [1, 2, 3]
```

Why is uniq used with parens here then?

**Comment by BetterCallSky** [comment]
Sorry for late reply.
`R.uniq` is a lazy function.  It could be possible to omit `()`, but I am not sure if there is any need for it.  
`R.toPairs` is not lazy (it's not possible to make it lazy). "data-first" and "data-last" use the same version.
