### ISSUE TITLE
Release 1.x.x

### ISSUE THREAD

**Issue by vlad-yakovlev** [remeda/remeda#194]
- [x] #202
- [ ] #205
- [ ] #155
- [ ] #41
- [x] #72
- [x] #78
- [x] #96
- [ ] #97
- [ ] #126
- [x] #147
- [x] #211

**Comment by vlad-yakovlev** [comment]
I've linked some issues that could be resolved in versions after 1.0.0. They look almost ready for development

Feel free to suggest more (plz, via issue link)

**Comment by eranhirsch** [comment]
I don't think we're following this as a roadmap anymore so I'm closing it
