### ISSUE TITLE
How to properly make use of pathOr()?

### ISSUE THREAD

**Issue by alixaxel** [remeda/remeda#20]
If I have a snippet like this:

```typescript
import { pathOr } from 'remeda';

let input = {
  a: {
    b: {
      c: 42,
    },
  },
};

let path = ['a', 'b', 'c'];
let output = pathOr(input, path, null);
```

Typescript complains the `path` variable does not satisfy the typings:

![image](https://user-images.githubusercontent.com/262782/61036303-c7a46980-a3c0-11e9-9c8c-4a7e40c9bcb6.png)

How can I properly make the above work?

Also, if I increase the nestedness to a fourth level:

```typescript
import { pathOr } from 'remeda';

let input = {
  a: {
    b: {
      c: {
        d: 42,
      },
    },
  },
};

let output = pathOr(input, ['a', 'b', 'c', 'd'], null);
```

I get the following error:

> Argument of type '["a", "b", "c", "d"]' is not assignable to parameter of type '["a", "b", "c"]'.
>   Types of property 'length' are incompatible.
>     Type '4' is not assignable to type '3'.ts(2345)

Looking at the source code, it seems that only typings up to the third level are provided?

---

PS: Thanks for putting work into remeda, it's very much needed. :+1:

**Comment by BetterCallSky** [comment]
What's your typescript version? Do you use strict mode?

**Comment by BetterCallSky** [comment]
1st example won't work because `path` has type `string[]`
2nd example doesn't work because we support only 3 level deep 😞  
 https://github.com/remeda/remeda/blob/master/src/pathOr.ts#L61

**Comment by alixaxel** [comment]
@BetterCallSky I see, makes sense for the 2nd (and easy to extend I guess).

As for the 1st example, is there a recommended way to type dynamic paths?

**Comment by BetterCallSky** [comment]
```ts
let path = ['a', 'b', 'c'] as ['a', 'b', 'c'];
```

**Comment by alixaxel** [comment]
@BetterCallSky Sorry for the long delay in reply, but the ` as ['a', 'b', 'c']` wouldn't work if I don't know the path beforehand. To give you an example where I'm coming from, I have some DB models for different entities, for instance:

```typescript
Suppliers
  .findByIdAndType('42', 'menswear')
  .get(['productsServicesSection', 'bespokeTailoring']); // boolean type
```

My `get` method implementation is simply a DB fetch call followed by call to `pathOr`:

```typescript
async get(key: string[] = [], fallback: any = null) {
  let data = await fetchRecord();

  if (key.length > 0) {
    return pathOr(data, key, fallback);
  }

  return data;
}
```

My question here is, how can I get what path I'm looking and have it typed?

The `as ['a', 'b', 'c']` workaround would require me to exhaustively list all the possibilities:

```typescript
if (key ===  ['a']) {
  return pathOr(data, ['a'] as ['a'], fallback);
} else if (key ===  ['a', 'b']) {
  return pathOr(data, ['a', 'b'] as ['a', 'b'], fallback);
} else if (key ===  ['a', 'b', 'c']) {
  return pathOr(data, ['a', 'b', 'c'] as ['a', 'b', 'c'], fallback);
}
```

Which is unfeasible. Having the consumer specify:

```typescript
Suppliers
  .findByIdAndType('42', 'menswear')
  .get(['productsServicesSection', 'bespokeTailoring'] as ['productsServicesSection', 'bespokeTailoring']);
```

Also seems a bit weird and very redundant...

Certainly there must be a more elegant way to do this?

**Comment by BetterCallSky** [comment]
workaround, skip type checking
```ts
 return pathOr(data, key as any, fallback);
```

The proper way to do it would be to add proper type annotations to the`get` function.  
Something similar to https://github.com/remeda/remeda/blob/master/src/pathOr.ts, but it's not easy 😞

**Comment by alixaxel** [comment]
@BetterCallSky Given that the current state of Typescript doesn't allow this behavior without rewriting the typings everywhere, I'm gonna go ahead and close this ticket then. Thanks for clearing this up!

**Comment by VWSCoronaDashboard8** [comment]
@lstkz this workaround for me didn't work because I wanted to use `undefined` as the fallback value and remeda didn't seem to accept that.

I was about to replace lodash with remeda, but straightaway tripped over this issue. I think it would be valuable to have a weakly typed version of this function for situations where you want to attempt to grab some unknown path value from any object. It would help the transition from what I think is quite common lodash code.
