### ISSUE TITLE
Support upperFirst

### ISSUE THREAD

**Issue by sushantdhiman** [remeda/remeda#207]
Please add [lodash/upperFirst](https://lodash.com/docs/4.17.15#upperFirst) equivalent

**Comment by TkDodo** [comment]
I'm pretty sure string helpers like that are not in-line with the remeda design goals. What we can do is add a good alternative to the one-line helpers in the mapping.md:
- https://github.com/remeda/remeda/blob/master/mapping.md#helpful-one-liners

it's basically:
`string.charAt(0).toUpperCase() + string.slice(1)`

**Comment by sushantdhiman** [comment]
It looks like similar requests have been raised in the past as well.

- #42
- #162

I understand that `upperFirst` is just a one-liner and can be implemented very easily in my code-base, but so do many different functions like `isNil` , `identity`, `reverse`.

There is a reason why there is a constant demand for these functions: they are extremely helpful. I don't want to implement (and test) these helper methods. That is why I am using `lodash` (or `remeda`).

I think at-least we shouldn't ignore helpers that are already available in `lodash`  and `ramada`. This library is not mainstream yet, and there is already a demand for string functions; it will only increase in the future.

If you want, I can submit a PR for this.

**Comment by TkDodo** [comment]
I really want to focus on object / array helpers instead of string helpers here, at least for now. If you want, please update the `mapping.md` with the suggested one-liner.
