### ISSUE TITLE
countBy unexpected behavior 

### ISSUE THREAD

**Issue by dany-fedorov** [remeda/remeda#210]
Did not expect `countBy` to work the way it works now. 
I expected it will be a `groupBy` where items in each group are counted, because that is what lodash does. 
Ramda seems to do the same.

1. [Ramda countBy](https://ramdajs.com/docs/#countBy)
2. [Lodash countBy](https://lodash.com/docs#countBy)

Also, current implementation effectively does the following, which is already simple enough
```js
array.filter(predicate).length
```
And on the contrary, to implement a `countBy` found in lodash/ramda, you need go some lengths in terms of code. I ended up writing the following
```js
  const counted = R.pipe(
    array,
    R.groupBy(predicate),
    R.toPairs,
    R.mapToObj(([k, v]) => [k, v.length])
  )
```
In my opinion, makes sense to change the behavior to conform with rambda and lodash, I'll be happy to make a PR

**Comment by TkDodo** [comment]
the behaviour of `countBy` is documented and the [mapping.md](https://github.com/remeda/remeda/blob/master/mapping.md) file does not mention that it works the same as in lodash. If we do this, it likely needs to be a different function, or it would be a breaking change

**Comment by dany-fedorov** [comment]
@TkDodo Do you like `groupByCounting` as a name for new function?

**Comment by TkDodo** [comment]
I also think we can consider putting a new impl for `countBy` on the v2 roadmap. I agree that it might be weird if other major libraries implement a functionality like that and remeda has a different name for it, but a function with the same name that does something different 🙃 @vlad-yakovlev what do you think?

**Comment by vlad-yakovlev** [comment]
@TkDodo we can deprecate countBy in future v1 update and replace it by next major release. This isn't optimal solution, I think, but could slightly help

**Comment by TkDodo** [comment]
yeah let's do that 👍
