### ISSUE TITLE
reusable omit

### ISSUE THREAD

**Issue by HardCoreQual** [remeda/remeda#211]
How can create reusable omit ?

```typescript
const omitId = omit(['id']);
const result = omitId({ id: 13, hello: 'world' }); // expected that result will have type { hello: string }
```

![Screenshot_2022-08-12_23-11-25](https://user-images.githubusercontent.com/28385162/184435601-4cc3dca1-dfdd-4bd7-b30f-5a096c7245f5.png)

```typescript
const omitId = <T extends { id?: any }>(e: T) => omit(e, ['id']); // but it not seems very good
```

**Comment by TkDodo** [comment]
I think if we change the types of `omit` to be:

```
export function omit<K extends PropertyKey>(
    names: readonly K[]
): <T extends { [key in K]: unknown }>(object: T) => Omit<T, K>;
```

it would work. Here's a [typescript playground](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXxwFssMAeAaXhAA8MRVgBneABRhwAcQYMBPckLwB8ACgBQ8eKiiEQjAFzw4UYHgi945ANoBdMQEpFpACpVa9JvADe8LQGtB8LPnI7FaO6hwB3fAF9RHAAjACtwDEVjfXgAXiF4AHliMmMAGk0hAG4xMTA8RgwCZIBJYFiikhEtAHIsYGqdfWy81AKlOWQIQpiKjFKRGzrFAEYAZnSACxAICBxFau8cGAh6+D8m+AB6TbMuTBAyjAmoQrhGTsLvLBn4Y4A3BD4ua1vp2cUCmGcAczWxbckkgAegB+HJnC4AOimMxw-x2AAEMIwALQ0PYYNEwdgwMQQrqQurw+BI1Ho8JYnF4joExA4HBAA) reproduction. We'd just need to make sure that this doesn't break `pipe` or other usages. @vlad-yakovlev what do you think?

**Comment by vlad-yakovlev** [comment]
Yeah, we can implement something like that for most of functions. Added to 1.x.x roadmap

**Comment by yanick** [comment]
#238 should take care of this
