### ISSUE TITLE
toPairs does not take Map as input

### ISSUE THREAD

**Issue by 0x80** [remeda/remeda#22]
It appears that toPairs doesn't take a Map as input, only POJO `{[key: string]: ...}` . Or are we supposed to use the Map's own toPairs() function? When piping functions this would be a bit odd I think.

**Comment by BetterCallSky** [comment]
Map is not supported. You can do:

```ts
R.pipe(
  map,
  m => [...m.entries()]
)
```

It's ok if you write your own function `toMapPairs`.

**Comment by 0x80** [comment]
Thanks, I guess that's fine. Although I think it makes sense to add support in Remeda toPairs in the future, like Lodash has.

BTW why are you placing the return value of entries() in a new array? I believe entries() returns a new array already so this would be more clean and efficient:

```ts
R.pipe(
  map,
  m => m.entries()
)
```

**Comment by BetterCallSky** [comment]
`m.entries()` returns MapIterator, `[...m.entries()]` converts it to an array

**Comment by 0x80** [comment]
I see, thanks!
