### ISSUE TITLE
maxBy / minBy should work with no callback for an array of numbers

### ISSUE THREAD

**Issue by jjhiggz** [remeda/remeda#230]
Was working on an advent of code problem today, I've been using lodash and switched to your library (it defnitely feels better to program in than lodash), but I noticed that your minBy and maxBy functions could probably be improved by making them work without a callback for arrays of numbers

for example I could have wrote this code

```ts
const getMinMaxData = (pairing: Pairing) => ({
  min1: minBy(pairing[0]) as number,
  min2: minBy(pairing[1]) as number,
  max1: maxBy(pairing[0]) as number,
  max2: maxBy(pairing[1]) as number,
});
```

instead of this code

```ts
const getMinMaxData = (pairing: Pairing) => ({
  min1: minBy(pairing[0], (n) => n) as number,
  min2: minBy(pairing[1], (n) => n) as number,
  max1: maxBy(pairing[0], (n) => n) as number,
  max2: maxBy(pairing[1], (n) => n) as number,
});
```

**Comment by TkDodo** [comment]
hm, I'm not sure. The function passed to all `...by` functions is mandatory. We can't really default it to `identity` because this only works well if you pass in an array of comparable things, like an `Array<number>`. If the array contains an object, the `identity` function would just compare objects. It's also an implicit behaviour that you would need to know.

For your use-case, currying works really well:

```
import * as R from 'remeda'
const minBy = R.minBy(R.identity)
```

with that, your "i could've written this code" example works.

**Comment by jjhiggz** [comment]
Had no idea you could do that, I guess it's the whole notion that you can choose either argument order with function overloading here.


Excellent work @TkDodo

**Comment by jjhiggz** [comment]
![Screen Shot 2022-12-04 at 10 24 17 AM](https://user-images.githubusercontent.com/59105254/205505755-35646fc3-d9c8-40f9-b9bb-bf5204059280.png)
@TkDodo I am getting this error when I try to do that

**Comment by jjhiggz** [comment]
But this worked just fine

```ts
const min = R.minBy((input: number) => input);
const max = R.maxBy((input: number) => input);
```

**Comment by TkDodo** [comment]
> Had no idea you could do that, I guess it's the whole notion that you can choose either argument order with function overloading here.

yeah all functions support data-first notations:

```
minBy(array, fn)
```

and data-last:

```
minBy(fn)(array)
```

this is what makes them work within a `pipe`.

> I am getting this error when I try to do that

yeah I was too fast with my answer. The pre-bound version doesn't know what to infer for `T`

What you can do is either provide the generic and bind it to `number`:

```
const minBy = R.minBy<number>(R.identity);
const result = minBy([1, 2, 3]);
```

or inline it with the data-last function:

```
const result = R.minBy([1, 2, 3], R.identity);
```
