### ISSUE TITLE
findLast and findLastIndex

### ISSUE THREAD

**Issue by LandonSchropp** [remeda/remeda#233]
Lodash and Ramda both include `findLast` and `findLastIndex` methods. These methods are just like `find` and `findIndex`, except they iterate through the array from back to front.

Would it be possible to add these functions to Remada?

Thanks!

**Comment by TkDodo** [comment]
yeah I think we could add that. Would you like to contribute it?

**Comment by LandonSchropp** [comment]
Sure! I opened #235.

**Comment by vlad-yakovlev** [comment]
Fixed in #235
