### ISSUE TITLE
Helper Functions from AOC, curious if they'd be useful for me to try and commit to Remeda

### ISSUE THREAD

**Issue by jjhiggz** [remeda/remeda#237]
Hey everybody, while doing AOC day 1 I saw a few functions that could be potentially useful to remeda:

## maxNBy

```ts
pipe(
  [1,4,6,2,6,3,7],
  maxNBy(3, el => el)
) // [7, 6, 6]
```

## minNBy

```ts
pipe(
  [1,4,6,2,6,3,7],
  minNBy(3, el => el)
) // [1, 2, 3]
```

## splitArrayWhen
```ts
pipe(
   [0,0,1,0,0,1,0],
   splitArrayWhen(n => n === 1)
) // [[0,0],[0,0],[0]]

```

The next few maybe aren't quite as sexy but they helped me write `maxNBy` / `minNBy`

## isArrayDecreasing - (only checks first and last elements right now)
```ts
pipe(
   [5,4, 3, 2, 1],
   isArrayDecreasing(el => el)
) // true
```

## isArrayIncreasing - (only checks first and last elements right now)
```ts
pipe(
   [5,4, 3, 2, 1],
   isArrayIncreasing(el => el)
) // false
```

## insertIntoSortedArray
```ts
pipe(
    [1, 2, 4, 5],
    insertIntoSortedArray(3, el => el)
) // [1, 2, 3, 4, 5]
```

```ts
pipe(
    [5, 4, 2, 1],
    insertIntoSortedArray(3, el => el)
) // [5, 4, 3, 2, 1]
```

I'm mainly just curious if the community would find these useful, I'd love to go through the process of building out these functions to be up to par with Remeda's typing / overloading strategy. I do probably have to learn a ton about function overloading, right now my implementations just assume the curried syntax

_DISCLAIMER: I'm not to great at open source but I really love this library and contributing seems like a great way for me to level up my typescript skills a bit._

**Comment by jjhiggz** [comment]
Out of curiosity am I able to just use the `purry` function to make this fit in?

**Comment by jjhiggz** [comment]
Also, I noticed that there is already a `splitWhen` I'm wondering if it would be more appropriate to add an `excludeSplitAtItem` option or something like that

**Comment by eranhirsch** [comment]
Hey @jjhiggz, sorry that you never got a reply. I'm not sure I understand maxNBy and minNBy, but `insertIntoSortedArray` is something I also found useful.

It's been a long time so i'm closing the task for housekeeping, but if you'd still want to see this happen i'll be happy to review a PR, just re-open the issue.
