### ISSUE TITLE
keys.strict regression on partial records

### ISSUE THREAD

**Issue by cloud-walker** [remeda/remeda#253]
I all, I've upgraded remeda to the latest version (1.6), and `keys.strict` now seems to produce `undefined` when interacting with partial objects:

```ts
import {pipe, keys} from 'remeda'

const data: Partial<Record<'foo' | 'bar', unknown>> = {foo: '1', bar: 7}
const result = pipe(
  data,
  keys.strict,
) // results type is 'foo' | 'bar' | undefined but in remeda 1.3 was only 'foo' | 'bar'
```

I currently think that the previous behaviour was the correct one.

I've seen the release changes, and maybe the bug comes from the v1.5.1? https://github.com/remeda/remeda/releases/tag/v1.5.1

**Comment by TkDodo** [comment]
yes, it's a regression from 1.5.1:

[typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzMMBTANHA1qgngZwF84AzKCEOAcilRFQBMBDKuAejbhlzXwC44ARgB0AVmGCAUJIDGEAHb54zGEwEAFJrGBMANgB4ASqjlQG+qiQgRWAH2oAjLVUwBXeVnkQA7vIB8fnAAvIhWEAJUgi5wTlACAOyEsgpKcLT4rrrwIchoABSScHAqTOiF2Hj4wkpQwDIwZQCU0umZMJIccAB6APxAA)
