### ISSUE TITLE
how to stop R.pipe(

### ISSUE THREAD

**Issue by reslear** [remeda/remeda#264]
how to stop R.pipe( without throw like rxjs switchMap?

```ts
const result = R.pipe(
  2,
  (x) => x * 2,
  (x) => x + 1,
  (x) => {
    // how stop is don'need next step?
    return undefined;
  },
  (x: any) => {
    console.log(12);
    return x * 3;
  }
);
```

**Comment by eranhirsch** [comment]
I don't think there's anything built in to Remeda that can do it, but you can build your own data-last component pretty easily. Typing becomes a little harder if you want it to be very generic, but a basic impl would look something like this:

```ts
function branch<T, RTrue, RFalse>(
  predicate: (data: T) => boolean,
  handleTrue: (data: T) => RTrue,
  handleFalse: (data: T) => RFalse,
): (data: T) => RTrue | RFalse {
  return (x) => predicate(x) ? whenTrue(x) : whenFalse(x);
}
```

You would use it like this:
```ts
  ... = pipe(
    ...
    branch((x) => x > 1337, createPipe(/* continue happy flow here */), createPipe(/* and else flow here */)),
    /* and anything after those branches can continue here */
  );
```

With better typing you can get type refinement for the branches, but that is more complex

**Comment by reslear** [comment]
@eranhirsch thx for this solution, need check)
But I probably didn't need the pipe here, went the usual way through For :) 

```ts
  for (const step of flows[flow]) {
    const [condition, nextRoute] = step()
    if (condition) {
      return nextRoute
    }
  }
```
