### ISSUE TITLE
Implement intersectWith

### ISSUE THREAD

**Issue by azhiv** [remeda/remeda#281]
It would be awesome to have this utility function available. Simply `intersect` is not enough, consider the following example:
```ts
const arr = [{ id: 1, name: 'Box' }, { id: 3, name: 'Present' }];
const ids = [3, 5];

intersectWith(arr, ids, (item, id) => item.id === id);
// [{ id: 3, name: 'Present' }]
```

**Comment by TkDodo** [comment]
would you like to contribute it?

**Comment by michal-weglarz** [comment]
@azhiv @TkDodo Since I haven't noticed any interest in this so far, I've decided to give it a shot myself in the PR #325
