### ISSUE TITLE
Incomplete mapping.md

### ISSUE THREAD

**Issue by 0x80** [remeda/remeda#29]
For people migrating from Lodash or Ramda it would be useful if the [mapping.md](https://github.com/remeda/remeda/blob/master/mapping.md) provides a complete list. Or is that not the goal of this file?

For example, I'm not sure how to replace the Lodash `times` utility...

**Comment by BetterCallSky** [comment]
Unfortunately, there is no replacement for `_.times`. Would you be interested in implementing it?

**Comment by SirJayEarn** [comment]
I think I can have a look at implementing `times` in the next couple of days

**Comment by leilapearson** [comment]
Have created related pr #53 to document some of the missing functions as Typescript one-liners.

Needs more discussion though...

**Comment by lewisl9029** [comment]
Since there's already a toPairs function, I found fromPairs to be a curious omission, as they go hand in hand. 

Would you be willing to accept a PR for it? Thanks!

**Comment by lstkz** [comment]
@lewisl9029 Sure, feel free to submit PR.
