### ISSUE TITLE
Make a documentation page for Ramda users

### ISSUE THREAD

**Issue by zkochan** [remeda/remeda#3]
Awesome package!

I really like how it works but it is hard for me to adopt as functions are named not the same way as in ramda. A page/table that shows what are the remeda equivalents of ramda functions (maybe with usage examples) would help a lot

**Comment by BetterCallSky** [comment]
Thanks!

What functions are missing or problematic? I could create a table with mapping, but most functions would be marked as `N/A` 😉. Many things can't be implemented in TypeScript, for example: lenses.

Examples are definitely on my TODO list.

**Comment by ivan-kleshnin** [comment]
My 5 cents. Ramda + TypeScript = PITA for sure.

I considered this library but argument flipping is so weird I decided to stay away. 

1) There are many IDEs with different behaviors 
2) Modelling a library after some particular IDE behavior is super strange IMO
3) We often refactor functions from `pipe` to pipe-less usage and vice-versa. Remembering to flip arguments each time we do that is not an option, unfortunately :(

Data-first is natural only for OOP fans.

**Comment by BetterCallSky** [comment]
@ivan-kleshnin 
Thanks for your feedback. Discussing here is really important.

RE 1. 2.
What IDE problems do you mean? VSCode is recommended for TypeScript projects. I've been using it for more than 1 year, and I don't have any problems.

RE 3.
Can you provide some examples?  
If you have a function call `Ramda.map(fn, data)`, and you convert it to pipe `Ramda.map(fn)`, you must remove 2nd argument, in Remeda you must remove 1st argument from `Ramda.map(data, fn)`.  
 I don't think it's problematic.

> Data-first is natural only for OOP fans.

I understand that people have different preferences, and it's not possible to create a library that will make 100% people happy.  My motivation was to create something that will work well with TypeScript, and I don't care about statements "this is OOP", "this is FP". This library was designed for developers who have similar understanding.  
There are use cases where you don't need any library like lodash/ramda/remeda.  
For example: when you map an array in React, you can use a native Array.map.
```jsx
{items.map(item => <Foo key={item.id} item={item} />)}
```
Some people try to write 100% FP in such simple code like above, even if there are no benefits of it. It's related to [this](https://en.wikipedia.org/wiki/Cargo_cult_programming).

**Comment by borekb** [comment]
Thanks for the mapping table, @BetterCallSky!

What's the recommended solution for situations where Remeda doesn't have an equivalent? For example, we often use `R.propEq` in Ramda, can Ramda and Remeda be mixed together? Or do you recommend writing own functions?

(Sorry for a newbie question, I'm just discovering this space; I generally like Ramda but have already encountered the TypeScript issues you describe so well in the README so am looking for alternatives...)

**Comment by BetterCallSky** [comment]
I don't recommend mixing multiple libraries together.  

For simple functions, you can write inline lambdas.
```ts
// instead of
R.propEq('hair', 'brown');

// write
x => x.hair === 'brown';
```

**Comment by borekb** [comment]
That's fine if your don't care about currying (to me, currying is one of the biggest reasons why to use these libraries). I didn't try if mixing and matching Ramda with Remeda would work, probably worth a test :)
