### ISSUE TITLE
TS errors in curried `pick`

### ISSUE THREAD

**Issue by KubaJastrz** [remeda/remeda#316]
This is fine:
```ts
pick(person, ['age'])
```
TS errors found:
```ts
pick(['age'])(person)
```

Perhaps the overload is malformed? It seems like it always uses the first one (with two parameters).

[Playground link](https://www.typescriptlang.org/play?#code/PTAECUFMFtIEwIagIwDpkBZUAYBQdIBjAGwQCdJQAzAVwDtCAXASwHs7QAHZwgawB4AKqEgAPRpDpwAzqFYAjAFZFGAGlABpEeMkzQvSAE9WVUIIB8ACgXKmALjPq6CWNIdQEcdsUMBBMmQIhvwa5gCUDgAKPAKC6qH4RKQU1PRMbBzcfELaElKyNirxubqyBsamFpbOru6Qnt5+AUEh4Q7WSioOgmGgALzmoNHZcZrmuLiMhpyUkZBk0uz9oADeuKAboDWQDtKMZMx0AOaq65sIRztbNNDy86cAvriE7Htc84t0UR9LfatnG22DgA5IJWHA4MDTptQBcrhgAEyPCZZXiWGYLdjqADawLhwIAumEUTFLLj8UT0T86MTnq9GFwYr5LstUWS8ZdCcTUczIFTMTTcEA)

**Comment by eranhirsch** [comment]
Thanks, this is because arrays in JS are objects, so typescript is using the first override for this method as it works (typescript is optimistic when assessing which overload to use).

I'll send a fix!

**Comment by eranhirsch** [comment]
This isn't a bug, typescript doesn't have enough typing information when in data-last if it's not part of a pipe. It can't infer the type of the data object, so it can't type the keys array properly.

In a pipe this would work because the pipe "assigns" a type to the data.


We could technically accept any keys instead of using a "keyof T", but that would require more work in typing the output, and I don't think that's a high priority.

**Comment by KubaJastrz** [comment]
Alright, thanks for the explanation.

**Comment by olsonpm** [comment]
Couldn't pick's data-last overload restrict the data to match the keys provided ?  e.g.

```ts
declare function pick<K extends PropertyKey>(
  names: ReadonlyArray<K>
): <T extends Record<K, any>>(object: T) => Pick<T, K>
```

**Comment by eranhirsch** [comment]
It could, and it would fix this specific way to use it, but it would make the code less strict when used in a pipe, which is what we optimize for when we design the data-last signatures.

The current typing makes it so that if you make a typo with your key name you will get a compilation error:

```ts
const myObject = { foo: 3, bar: "hello" } as const;


const result = pipe(
  myObject,
  // @ts-expect-error -- "baz" does not extend "foo" | "bar"
  pick(["baz"]),
);
```

**Comment by olsonpm** [comment]
Got it - thanks for the explanation.  I'm building a different type of functional library and referencing this one to learn how 'yall typed it.  Learning a lot but also realizing the many limitations of ts
