### ISSUE TITLE
Question: Example removing undefined from array?

### ISSUE THREAD

**Issue by mcgrealife** [remeda/remeda#319]
Can Remeda be used as a **helper to remove undefined from an array**?

```ts
const array = [{ item: 1 }, undefined]
```

I've tried combinations of `R.filter`, `R.map`, `R.isTruthy`.

This is not an issue (unsure where else to post).

Thank you!

**Comment by eranhirsch** [comment]
Would `R.filter(array, R.isDefined)` work?
