### ISSUE TITLE
Helper to check if all object values are Truthy?

### ISSUE THREAD

**Issue by mcgrealife** [remeda/remeda#324]
```
const obj = { 
  key1: 1,
  key2: 2,
  key3: null
}
```

Goal:

`if (any keys are null) return`

Something like

`if ( R.anyKeysNil(obj) ) return`

**Comment by eranhirsch** [comment]
We could create wrappers around `Array.some` and `Array.every` but beyond that you could do this with R.keys(obj).some(R.isNil())

**Comment by mcgrealife** [comment]
wonderful, I am quickly becoming addicted to this library. Thank you @eranhirsch
