### ISSUE TITLE
Pipe item not receiving guarded value?

### ISSUE THREAD

**Issue by mcgrealife** [remeda/remeda#326]
Attempting to `R.filter()` for null, and pass the guarded value to `R.sortBy()`
```ts
R.pipe(
  [1, null],
  R.filter(n => R.isTruthy(n)), // isTruthy<number | null>(data: number | null): data is number
  R.sortBy(n => n) // error: Type 'null' is not assignable to type 'Comparable'.
)
```
The `R.sortBy` predicate is still receiving `n` as `number | undefined`

Am I using this incorrectly?

**Comment by eranhirsch** [comment]
Don't recreate the arrow functions, use the data-last version of R.isNil in the filter

**Comment by mcgrealife** [comment]
Wow, major "click" moment. Thanks as always @eranhirsch, your support is rare and appreciated.

Also, thanks for the new R.isNonNull release, I am updating Remeda now!

**Comment by mcgrealife** [comment]
I encountered a similar case and am struggling to apply your answer when the **input is an array of objects**:

This R.filter only checks if the object isNonNull, not the object's values
```ts
R.pipe(
  [{ number: 1 }, { number: null }],
  R.filter(R.isNonNull),
  R.sortBy((x) => x.number) //  Type 'null' is not assignable to type 'Comparable'.
```

Maybe you have a better way. Thank you as always @eranhirsch

**Comment by eranhirsch** [comment]
Your filter is not doing what you think it's doing. Check out your IDE's typehint tooltips. You are filtering objects which are null, not the prop within them. Remeda doesn't have (at least rn) a way to filter and narrow the type of a prop within an object. You'll need to write something yourself.

```ts
function hasNumber(obj: { number: number | null }): obj is { number: number } {
  return obj.number !== null;
}
```
