### ISSUE TITLE
Feature Request: swap element in Array 

### ISSUE THREAD

**Issue by hyousi** [remeda/remeda#332]
https://ramdajs.com/docs/#swap 

I this the `swap` function is extremely useful because it's a common use case in drag-and-drop. 

Ramda provides the `swap` function in the latest docs. It has been 8 years since the first feature request about the swap in lodash-js, but it's still working in progress...

**Comment by eranhirsch** [comment]
I think this is a great addition, would you want to try sending a PR for it?
