### ISSUE TITLE
Nested object to object of key tuples

### ISSUE THREAD

**Issue by cloud-walker** [remeda/remeda#335]
Hi all!

I'm using the library from quite some time now, this time I want to extract the keys (as a tuple) from a nested object, here an example: 

```ts
const variants = {
  size: {
    lg: '...',
    md: '...',
    sm: '...',
    xs: '...',
  },
  mode: { 
    outline: '...', 
    subtle: null 
  },
  tone: {
    gray: '...',
    blue: '...',
    indigo: '...',
    purple: '...',
  },
} as const
```

I want create an object that takes the nested objects and convert them in an array of keys, preserving the typings as strict as possible, what I want is:

```ts
type Foo = {
  size: ['lg', 'md', 'sm', 'xs']
  mode: ['outline', 'subtle']
  tone: ['gray', 'blue', 'indigo', 'purple']
}
```

I've tried using a combination of `mapValues` and `keys.strict`, with no success (the resulting type is more opaque):

<img width="968" alt="image" src="https://github.com/remeda/remeda/assets/1144075/b1846909-99cf-46e5-b083-b2e010b9a2f7">

You have any (pun intended) suggestions to achieve what I want?

**Comment by eranhirsch** [comment]
I don't think this is possible with remeda without needing to write a new function just for this. I'm not even sure you can do this with typescript, you'd need some elaborate mapping.
```ts
type NestedKeys<T> = { [P in keyof T]: (keyof T[P])[] }
```

But even this type can't "enforce" that you'd have exactly one value for each key, for your example the following object is also valid:
```ts
const x: NestedKeys<typeof variants> = { size: [], mode: [], tone: [] };
```

which isn't very useful.

Try see if you can build a better type via utils in [type-fest](https://github.com/sindresorhus/type-fest).
