### ISSUE TITLE
Generate testing suites using a ChatGPT-4 CLI wrapper

### ISSUE THREAD

**Issue by MauricePasternak** [remeda/remeda#341]
Great project you guys have here. I wanted to suggest the idea that this CLI tool can potentially help you generate very robust unit test suites:

https://github.com/Pythagora-io/pythagora

It seems to excel in standalone functions and even advertises itself for having found bugs in Lodash.

**Comment by erikbower65** [comment]
Thanks @MauricePasternak for sharing the useful information. Find it from [Codium](https://github.com/Codium-ai).

**Comment by eranhirsch** [comment]
This sounds great, we'd be happy to review any PR that adds more and better tests for Remeda.
