### ISSUE TITLE
lint for correctness

### ISSUE THREAD

**Issue by TkDodo** [remeda/remeda#347]
we can use:
- attw: https://arethetypeswrong.github.io/?p=remeda%401.24.0
  - ✅ all good right now
- publint: https://publint.dev/remeda@1.24.0

`publint` currently shows lots of warnings

we could include both tools in our CI pipelines

**Comment by eranhirsch** [comment]
These are really cool, I tried looking into the suggestion that publint raises but it's too complex for me, do you know how to fix it?
