### ISSUE TITLE
`filterValues` for filtering objects

### ISSUE THREAD

**Issue by dartess** [remeda/remeda#348]
I started migrating from ramda and found that I was missing `filter` for objects. It's like `mapValues` but `filter`:

```
R.filterValues({ a: 1, b: 2 }, (value) => value > 1) // => { b: 2}
```

`filter` from ramda work as `filterValues` for objects.

**Comment by TkDodo** [comment]
yeah we have `mapValues`, so a `filterValues` would be good, too. Would you like to contribute it ?

**Comment by dartess** [comment]
Lol, I went to look if there is a key filter in ramda. And found `pickBy`. Then I found `pickBy` in remeda. Issue can be closed 😅 

If we add `filterValues` and `filterKeys`, these will be small wrappers over `pickBy` with fewer arguments in the predicate. Doesn't sound helpful anymore.
