### ISSUE TITLE
Request for new binary search based indexing functions

### ISSUE THREAD

**Issue by envil** [remeda/remeda#353]
It would be nice to have binary search function implemented like in lodash:

https://lodash.com/docs/4.17.15#sortedIndex
https://lodash.com/docs/4.17.15#sortedIndexBy
https://lodash.com/docs/4.17.15#sortedIndexOf
...

**Comment by eranhirsch** [comment]
Sounds good. Would you like to contribute these? I'd be happy to review, approve, and merge

**Comment by envil** [comment]
Sure, I will give it a try. Thanks.

**Comment by eranhirsch** [comment]
hey, just pinging to let you know I had an implementation of this in one of my projects so i'm sending a PR to include this.

**Comment by eranhirsch** [comment]
This is done, would be part of the next remeda release

**Comment by envil** [comment]
Great work, thank you!
