### ISSUE TITLE
Problem with `mapValues` types

### ISSUE THREAD

**Issue by dartess** [remeda/remeda#354]
For some strange reason, I'm getting a key type compatibility error. In the callback, the key is described as a string. I can't pass it into `mapValues` because I get the error:

```
TS2345: Argument of type
(order: Order, id: string) => BotOrder
is not assignable to parameter of type
(value: Order, key: string | number) => BotOrder
Types of parameters  id  and  key  are incompatible.
Type  string | number  is not assignable to type  string 
Type  number  is not assignable to type  string 
```

I tried to simplify the example and reduced it to this demonstration of the problem:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbziAhmAaigNgVwKYDOcAvnAGZQQhwBEUeIeAJijQNwCwAUNzAJ5g8cAPJQmeKHAC8iOMCYAuOADscIAEYSSnLgGMIygvGjioBAEp59YpZetMAPEajBlAcwA0IsRIB80xGIdfUNjHzMASWVxAA9mJSQAbQBrPD4lZ1c3AF0lUVMSAIQg7lKuVAxsfAIACm44OBMJCysTD3q4GqaoL3kASml-VSwsdq4GiYaAeim4AD0Afm4+nQrMXEI68cbwgijY5jGGrvDepgGpIZwRo8np2cXlnSA

Since I can't figure out where the difference between an index signature and a Record comes from, I suggest fixing the bug at the `remedy` type level. To do this, it is enough to add intersections with strings to the keys. This will be correct, because the implementation uses `Object.keys`, which always returns only strings anyway.

I can do a PR for this.

**Comment by eranhirsch** [comment]
This isn't related to remeda, I don't know why `keyof` for an indexed object return `string | number`.

https://www.typescriptlang.org/play?#code/MYewdgzgLgBATgU1HAJgLhgbxgbQNIwCWYM0cxA5gLoYBEKArgLZMCetMAvjALxacBuALAAoUJFjEUCAB4J0WXAGsErDGUo0Y9Zmw7c+mQaNFRWABwTwkIVHlUReMFaxAAzGGcvvryFMJEAekCYUIA9AH5TCyspWXtWRz4XHy8EHzi5f1Fg0JhIoA

mapValues simply types the key as `keyof T`, it's doing what it's supposed to do here

**Comment by dartess** [comment]
Yes but it can be easily fixed in remeda via `keyof T & string`

**Comment by eranhirsch** [comment]
I don't know why it's being typed as number, but it means that typescript thinks the key could be a number too, and if anyone is relying on this being the case we would break their assumption and code. If the type should be just `string` typescript would have inferred that

**Comment by eranhirsch** [comment]
Looking at this again, I think you might be right! The key could be `string | number` but that just because you can use a number to index the object. The mapper itself uses Object.keys() which only returns string keys...

I don't mind reviewing a PR to fix this!

Sorry for the misleading first answer again!

**Comment by eranhirsch** [comment]
So thinking about this some more, it feels like the type for the key should be ``${keyof T}``. It would cover a type like `{ [index: number]: unknown }` properly.

@dartess, wdyt?

**Comment by dartess** [comment]
@eranhirsch i got an error with `${keyof T}`. But `${Exclude<keyof T, symbol>}` looks working and better than `keyof T & string`. I, too, will think a little more and experiment, after which I will do a PR.
