### ISSUE TITLE
`sort` should support a list of comparators

### ISSUE THREAD

**Issue by KazimirPodolski** [remeda/remeda#367]
Same as `sortBy`. Alternatively `sortBy` should support comparators.

A use-case for that is sorting strings with [localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) _(you are not sorting your strings with `a < b`, right?)_ plus some other field to make the order stable in case of equals. E.g. order users by name - you want to sort by name and then sort by something else like creation date.

**Comment by eranhirsch** [comment]
I think the API for sortBy would become too complex if we add anymore to it, it's already pretty complex, it's also a big advantage of that function that it hides the comparison itself, unlike most sorting APIs (so I can do `sortBy(prop('a'), prop('b'), prop('c')` and each prop might have a different type).

For `sort`, it seems like it wouldn't reduce much boilerplate over just adding the complexity directly to the comparator:
```ts
pipe(
  ...
  sort((a, b) => {
    const result = a.prop1.localeCompare(b.prop1);
    return result === 0 ? a.prop2 - b.prop2 : result;
  }),
  ...
);

vs
pipe(
  ...
  sort(
    (a, b) => a.prop1.localCompare(b.prop1),
    (a, b) => a.prop2 - b.prop2,
  ),
  ...
```

wdyt?

**Comment by KazimirPodolski** [comment]
I agree about `sortBy`, tho adding an API which is clearly distinct from others by type is maybe fine?.. But "one arg function" vs "two args function" is not enough.

On `sort`, in your example the second case is more readable and clearly shows intent (as long as the user knows the semantic of sort with multiple args), while in the first one has to actually read the code. The differrence is bigger the more comparators there are:

```typescript
pipe(
  users,
  sort((a, b) => {
    const byName = a.name.localeCompare(b.name);
    const byRating = a.rating - b.rating;
    return byName === 0 ?
      (byRating === 0 ? a.createdAt.valueOf() - b.createdAt.valueOf() : byRating) :
      byName;
  })
);

pipe(
  users,
  sort((a, b) => {
    const byName = a.name.localeCompare(b.name);
    if (byName !== 0) return byName; // tho braceless one-line ifs are banned by lint in some/many companies
    const byRating = a.rating - b.rating;
    if (byRating !== 0) return byRating;
    return a.createdAt.valueOf() - b.createdAt.valueOf();
  })
);

pipe(
  users,
  sort(
    (a, b) => a.name.localeCompare(b.name),
    (a, b) => a.rating - b.rating,
    (a, b) => a.createdAt.valueOf() - b.createdAt.valueOf()
  );
);
```

**Comment by eranhirsch** [comment]
I don't mind allowing `sort` get multiple comparators if you want to send a PR for it. I don't think it should contain a direction, directions are "baked into" the comparator by negating the value, this adds complexity beyond what it's worth.

**Comment by KazimirPodolski** [comment]
Let me get further with my pet project, I'll see how I actually want to do that.
