### ISSUE TITLE
isEmpty doesn't accept falsy input

### ISSUE THREAD

**Issue by TkDodo** [remeda/remeda#369]
we ran into this issue today, consider the following:

```
type User = {
  id: number
  firstName: string | undefined
}
declare function getUser(id: number): User | undefined

const user = getUser(1)
const hasFirstName = isEmpty(user?.firstName)
```

this errors because we can't pass `undefined` to `isEmpty` ([TypeScript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzsAzgUXDAnnAvnAMyghDgHIoBTESgEwEMyAoJ7MSuAVRUqjgF5ETOMloAuOADsAriABGvYYWBQUMAHL0aEtVGCSA5nAA+caZNqUC+uk1xNLAYwA29KoXOOYwCJLgHKGG5eAApgcSlZBSgASglgvlNzS2tJWyZHXzUzHj5BAKDckIBGGJZMyWyAC3oUADEVNU0aAWR0TCwQ6VyAfgA6a1UNLUoYoA)). One workaround is to either check upfront explicitly:

```
const hasFirstName = user?.firstName ? isEmpty(user.firstName) : false
```

or coerce to empty string:

```
const hasFirstName = isEmpty(user?.firstName ?? '')
```

both of which are kinda weird. Imo, "a function that checks if the passed parameter is empty" (from the docs) could consider accepting `null` and `undefined` and return `true` for them being "empty".

What do you think @eranhirsch ?

**Comment by TkDodo** [comment]
here's a diff that I think would accomplish this:

```diff
diff --git a/src/isEmpty.ts b/src/isEmpty.ts
index b42b70c..fc73d57 100644
--- a/src/isEmpty.ts
+++ b/src/isEmpty.ts
@@ -22,6 +22,7 @@ export function isEmpty(data: ReadonlyArray<unknown> | []): data is [];
@@ -22,6 +22,7 @@ export function isEmpty(data: ReadonlyArray<unknown> | []): data is [];
 export function isEmpty<T extends Readonly<Record<PropertyKey, unknown>>>(
   data: T
 ): data is Record<keyof T, never>;
+export function isEmpty(data: null | undefined): true;
 export function isEmpty(data: unknown): boolean {
   if (isArray(data) || isString(data)) {
     return data.length === 0;
@@ -29,5 +30,5 @@ export function isEmpty(data: unknown): boolean {
   if (isObject(data)) {
     return Object.keys(data).length === 0;
   }
-  return false;
+  return data == null;
 }
```

**Comment by eranhirsch** [comment]
When I reviewed the original PR my fear was that any relaxation of typing would allow *some* bugs to fall through, this is the reasoning behind typescripts strictest configs which are not enabled by default (like exactOptionalPropertyTypes). Zod have the same issue where `optional()` object properties return a type which has `undefined` in it.

Because remeda isn't configurable, we need to make a decision on how strict our types should be. I prefer strictness, but understand this isn't everyone's cup of tea.

Your example could be shortened to:
```ts
const hasFirstName = user === undefined ? false : isEmpty(user.firstName);
```

and I think that's descriptive enough, think about a different use-case. It's not always obvious what the undefined case should return, it's not always going to be false.
```ts
const hideWelcomeGreeting = user === undefined ? true : isEmpty(user.firstName);
```

**Comment by TkDodo** [comment]
> Your example could be shortened to:

> const hasFirstName = user === undefined ? false : isEmpty(user.firstName);

not exactly because the `firstName` itself is also optional.

> Because remeda isn't configurable, we need to make a decision on how strict our types should be.

we always have the option of adding stricter types to the `.strict` namespace?

**Comment by eranhirsch** [comment]
true, but that doesn't address what should be the default returned value for isEmpty(undefined), is it true or false?

**Comment by TkDodo** [comment]
I think it should be `true`, given that we agree that `undefined` and `null` can both be considered `empty` (for whatever `empty` means in that terminology 😅 )

**Comment by eranhirsch** [comment]
Facebook's Hack standard library define null as true for strings (and strings only) and doesn't accept nulls for collections. I don't mind going with this...

https://docs.hhvm.com/hsl/reference/function/HH.Lib.C.is_empty/
https://docs.hhvm.com/hsl/reference/function/HH.Lib.Str.is_empty/

**Comment by TkDodo** [comment]
yeah I would also not allow null for collection-only methods like `flatMap` (I think we had a separate discussion about this), but here, were strings are also allowed, I think it would be a better DX.

**Comment by eranhirsch** [comment]
Checkout the #377 that solves this. My only issue is that we will now accept isEmpty(undefined) too, and I couldn't find a way around it so users lose some protection against cases like: `isEmpty(obj["typo"])`
