### ISSUE TITLE
[ Feature Request ] Flow from fp-ts

### ISSUE THREAD

**Issue by Visual-Dawg** [remeda/remeda#383]
Hey, I love this library. 
The only thing I find missing is the function `flow` from `fp-ts`, which is like a curried `pipe`.

Can you implement it, please? :)

[Here is the code](https://github.com/gcanti/fp-ts/blob/master/src/function.ts#L236C2-L236C2) and [here are the docs about it](https://gcanti.github.io/fp-ts/modules/function.ts.html#flow)

**Comment by eranhirsch** [comment]
We have `createPipe` which is exactly a curried pipe. Does that answer your needs?
https://remedajs.com/docs#createPipe

**Comment by Visual-Dawg** [comment]
Thats perfect, thank you
