### ISSUE TITLE
[ Feature Request ] Lodash "matches" function (Also typing "equals")

### ISSUE THREAD

**Issue by timspro** [remeda/remeda#386]
I'm looking at using a more TypeScript-oriented utility library after using Lodash. This library seems very nice. However, there does not seem to be a way to check if one object is a subset of another (?). This is pretty common functionality in Lodash like`_.find(data, {a: "b"})`. Right now, one could do `R.find(data, ({a}) => a === "b")`; however, when there are more properties it becomes more burdensome to write out the callback. I realize that you could also do something like `R.find(data, R.createPipe(R.pick(['a']), R.equals({a: "b"})))`, but this is also pretty verbose.

To be clear, I'm not looking for the "iteratees" notation, which I don't think makes sense with typings, but rather just the "matches" function: https://lodash.com/docs/4.17.15#matches. This would be similar to the R.prop function in terms of usefulness. So the example above would become `_.find(data, R.matches({a: "b"}))`.

I also took a look at the R.equals implementation to see if maybe that could be used (doesn't seem so), and I noticed the typing permitted comparing any type to any type. I can see why this makes sense, but I do think it is somewhat of a logical error to compare two things of different types and I would want the compiler to warn about it. If it is intended by the programmer, then there are ways to coerce the types to get around the type check. Maybe it would make sense to have an "R.equals.typed" function with the same implementation but a different typing?

The typing I would like for a "matches" function:
```ts
export function matches<U extends string | number | symbol, V, T extends Record<U, V>>(
  subset: T
) {
  return <S extends T>(object: S) => {
    ...
    return true
  }
}
``` 
This allows for the compiler to error when doing something like `matches({ b: 1 })({ a: 3, b: "a" })` or `matches({ c: 1 })({ a: 3, b: "a" })`.

**Comment by eranhirsch** [comment]
I wouldn't mind including a matches function, would you like to send the PR that adds it? I'd be happy to review and merge it.

I think the name `matches` is problematic as it doesn't communicate the meaning clearly enough, I think it should be named `isSubObjectOf`.

**Comment by cjquines** [comment]
ramda calls this [`whereEq`](https://ramdajs.com/docs/#whereEq), because it also has `where` and `propEq` and `whereAny`

im a fan of the name `extendsObj`

**Comment by pascal-zinke** [comment]
I think a `propEq` like in ramda would be really useful as well

**Comment by cjquines** [comment]
@timspro can you look at the pr and check if the typing is good? notably, all of these would be type errors:

```ts
    // @ts-expect-error - missing a key
    hasSubObject({ a: 1 })({ b: 2 });

    // @ts-expect-error - wrong value type
    hasSubObject({ a: 1 })({ a: "a" });

    // @ts-expect-error - wrong value type
    hasSubObject({ a: 1 })({ a: 2 } as unknown);

    // @ts-expect-error - wrong value type
    hasSubObject({ a: 1 } as const)({ a: 2 });
```
