### ISSUE TITLE
[Feature Request] Index as a union on strict indexed functions

### ISSUE THREAD

**Issue by nevnein** [remeda/remeda#389]
While eg. mapping on tuples the index argument could be defined as `0 | 1 | … | n-1` instead of just `number`

## Motivation
Suppose we're working with `noUncheckedIndexedAccess: true` and we're mapping over a tuple, we might want to access some other tuple of the same length. 
```ts
const aTuple = [ "a", "b", "c" ] as const
const bTuple = [ "x", "y", "z" ] as const

R.map.strict.indexed(aTuple, (_, i) => {
  // With noUncheckedIndexedAccess: true the below is inferred as possibily undefined, 
  // but TS could/should know that the the index will always be 0 | 1 | 2
  const access = bTuple[i]
  //    ^? "x" | "y" | "z" | undefined
})
```
As seen above, right now the resulting type includes `undefined`, even though we know the tuples are of the same length.
However, should the index type be a narrower `0 | 1 | 2` instead of just `number`, everything will be fine.

```ts
declare const safeIndex: 0 | 1 | 2
const safeAccess = bTuple[safeIndex]
//    ^? "x" | "y" | "z"
```
Note that in the event of tuples of different lengths (user error) TS still errors and rightfully so.
```ts
const cTuple = [ "0", "1" ] as const

const unsafeAccess = cTuple[safeIndex]
//    ^? Error: Tuple type 'readonly ["0", "1"]' of length '2' has no element at index '2'.
```

## Performance concerns
A union type might look scary on the performance side of things, but this change should impact only the `strict` version, ergo tuples, which in all fairness will rarely (probably never?) have a length > 10

**Comment by eranhirsch** [comment]
If you want to send a PR to see how this could be done i'd be happy to take a look. My concern is that we have some abstraction around indexed functions which might be hard to adjust for this. Also in general it feels like making a stricter type of `zip` which could build a tuple and not just an array might just be more ergonomic overall

**Comment by nevnein** [comment]
I'll take a look at making a stricter `zip`, thank you!
