### ISSUE TITLE
[Feature Request] Adding Ramda's `assocPath` or Changing implemantation of `setPath` 

### ISSUE THREAD

**Issue by fneco** [remeda/remeda#396]
This issue proposes the addition of a new function to the remeda library or addition of new functionality to existing funciton.

## Proposal 1

I would like to add to `setPath` the ability to add data to a new path.

|      | array    | object   | array and object (with array of props) |
| ----------- | -------- | -------- | -------------------------------------- |
| read data   | `prop` | `prop` | `pathOr`                             |
| set data    | \-       | `set`  | **`setPath`**  (new)                        |
| delete data | \-       | \-       | \-                                     |
| update data | \-       | `set`  | `setPath`                            |

## Proposal 2

I would like to add a function that can  add data to a new path.

| rEmEda      | array    | object   | array and object (with array of props) |
| ----------- | -------- | -------- | -------------------------------------- |
| read data   | `prop` | `prop` | `pathOr`                             |
| set data    | \-       | `set`  | **`assocPath`**  (new)                      |
| delete data | \-       | \-       | \-                                     |
| update data | \-       | `set`  | `setPath` / **`assocPath`** (new)          |

## Motivation

the `setPath` function can update data of existing path, but can't add data to new path.
The following test code will not succeed.

```ts
  test('should set a deeply nested value', () => {
    // @ts-expect-error
    expect(setPath({}, ['a', 'b'], 2)).toEqual({
      a: {
        b: 2,
      },
    });
  });
```

### As-Is RAMDA implementation for read/set/delete/update data by specifying property

| rAmda       | array                   | object     | array and object (with array of props) |
| ----------- | ----------------------- | ---------- | -------------------------------------- |
| read data   | `nth` / `prop`      | `prop`   | `path`                               |
| set data    | `insert` / `assoc`  | `assoc`  | `assocPath`                          |
| delete data | `remove` / `dissoc` | `dissoc` | `dissocPath`                         |
| update data | `update` / `assoc`  | `assoc`  | `assocPath`                          |

version: v0.29.1

### As-Is remeda implementation for read/set/delete/update data by specifying property

| rEmEda      | array    | object   | array and object (with array of props)             |
| ----------- | -------- | -------- | -------------------------------------------------- |
| read data   | `prop` | `prop` | `pathOr`                                         |
| set data    | \-       | `set`  | \-<br>\* `setPath` don't have this functionality |
| delete data | \-       | \-       |\-                                                   |
| update data | \-       | `set`  | `setPath`                                        |

commit hash: 78075dc

**Comment by eranhirsch** [comment]
I think we can merge this with #397, it's generally the same.

**Comment by TkDodo** [comment]
let's track this in #397
