### ISSUE TITLE
[Feature Request] Result type

### ISSUE THREAD

**Issue by Visual-Dawg** [remeda/remeda#399]
I really like this library. It has the best typings for functions and works really well.
However, I miss the `Result` type provided by `fp-ts` and [`ts-belt`](https://github.com/mobily/ts-belt), as it makes error handling so much nicer.

So I switched to `ts-belt`, but the typings do not work that well and development seems a bit stalled.
Thus instead, I propose this feature request here :)

Also, if this gets accepted also adding utilities for an `Option`-type, which just act on `type | undefined`, instead of its own `Option` object would be really cool!

Cheers

**Comment by eranhirsch** [comment]
I have no context here, can you provide an example of how the API would look like and what advantages it provides?

Generally speaking we have only a handful of places where the library throws on error, and we usually try to make the type as strict as possible to prevent users from using erroneous input values.

**Comment by Visual-Dawg** [comment]
The library itself does not to return a `Either`/`Result` type. 
This type is simply generally very useful for handling Errors in a standardized way, while also improving the typings, as the error becomes visible in the type and needs to get handled.

Here is the API of ts-belt: https://mobily.github.io/ts-belt/api/result

**Comment by eranhirsch** [comment]
As I mentioned, we have very few cases of returning errors in general, and you are asking to change the return value for **all** functions in remeda; this is a huge change that would break everyone's existing code. It is unlikely that this would meaningfully improve the library for most use cases and users.

Can you provide an example where the current solution is lacking and your proposed solution helps? Without a concrete example, I just don't understand the ask here.

cc: @TkDodo - Am I missing something here?

**Comment by Visual-Dawg** [comment]
Sorry, my wording seems to be a bit off. 
I dont mean that anything else should change. Only to add/export a `Result` type and functions for it, like `map` (`rMap maybe?).

**Comment by TkDodo** [comment]
we would need to add a lot of util functions that works with Results, or versions of existing utils that work with Results. Are you maybe looking for something like effect?

- https://github.com/Effect-TS/effect

**Comment by Visual-Dawg** [comment]
True and yes I laid an eye upon `effect-ts` :D
