### ISSUE TITLE
point free pick / omit types are not working

### ISSUE THREAD

**Issue by cloud-walker** [remeda/remeda#408]
Using pick or omit functions in a pipe for example, does not autocomplete the object keys coming from the pipe (and does not type check them).

```ts
import {pipe, omit} from 'remeda'

pipe({foo: 'hello', bar: 123}, omit(['asdf'])) // this should give a ts error
```

I've tried various remeda versions from the 1.29 to the 1.20 without luck 😢 

Here a repro: https://codesandbox.io/s/remeda-point-free-pick-omit-types-jx9m4j?file=/index.ts

**Comment by eranhirsch** [comment]
Hey, this might be the case, we did some changes a few months ago to the dataLast implementation of these functions and we observed some issues (which were already fixed for `prop`). We might need to replicate those fixes to other functions.

If you want to take a stab at it i'd be happy to review as my bandwidth is limited recently. If not, i'll try and fix it myself soon(ish)

**Comment by cloud-walker** [comment]
Sure! You can you share some information to start with? (Like the `prop` fix PR)
