### ISSUE TITLE
add mergeDeep

### ISSUE THREAD

**Issue by geekflyer** [remeda/remeda#41]
Hi,

great work with this library!

I was wondering if you could add a mergeDeep (mergeDeepLeft or mergeDeepRight) to the library? That is especially useful to merge defaults into nested config objects etc.

Thanks

**Comment by lstkz** [comment]
Hi,

Sorry for the delay. Would you be interested in submitting a PR?

**Comment by lstkz** [comment]
Here is a pending PR https://github.com/remeda/remeda/pull/69

**Comment by hgezim** [comment]
Any movement on this?

**Comment by TkDodo** [comment]
there was no movement, so I closed the PR. if you want to pick it up - please go ahead :)

**Comment by yanick** [comment]
Fwiw, I ported `updeep`, a small utility package that focuses on deep merging of immutable objects to use Remeda as its underlying engine: https://github.com/yanick/updeep-remeda/

**Comment by eranhirsch** [comment]
Being handled in #317
