### ISSUE TITLE
`debounce` utils

### ISSUE THREAD

**Issue by no1flash** [remeda/remeda#419]
For example, I'd like to delay state update when input value changes,
have any plans to implement debounce utils?

**Comment by eranhirsch** [comment]
Can you please provide an example of the inputs and outputs that this function would produce? Alternatively, could you share a link to a similar function in Lodash or Ramda?

**Comment by no1flash** [comment]
Thank you for update `debounce` functions  : )
I checked the pr and confirmed that  is what I want !
