### ISSUE TITLE
Plans to support case changing functions?

### ISSUE THREAD

**Issue by chmac** [remeda/remeda#42]
Firstly, thanks for this library, first class typescript support is super awesome!

I was looking for a typescript friendly alternative to lodash hoping to use `_.upperFirst()` which changes the first character of a string to uppercase. Any plans to add such case changing functionality to remeda?

**Comment by SirJayEarn** [comment]
I personally don't see this being used very often. This could also be achieved pretty easily without the need of an external utility library:

```
const firstUpper = (str: string) => `${str.substring(0, 1).toUpperCase()}${str.substring(1)}`
```

**Comment by chmac** [comment]
Sure, upperFirst is a relatively easy example. Camel, kebab, snake, start case, etc are a bit harder.

**Comment by lstkz** [comment]
We could support it, but only ASCII version. Lodash supports Unicode https://github.com/lodash/lodash/blob/master/.internal/unicodeWords.js, and it seems to be too complex.
