### ISSUE TITLE
Add `add` and `multiply` functions.

### ISSUE THREAD

**Issue by LandonSchropp** [remeda/remeda#439]
These simple functions add and multiply two numbers.

This is useful when determining `sums` and `products` of arrays of numbers.

```
[1, 2, 3, 4].reduce(R.add); // 10
[1, 2, 3, 4].reduce(R.multiply); // 24
```

For completeness, it might also be worth adding `subtract` and `divide`.

All four functions are implemented in both Lodash and Ramda.

Separately, `sum` and `product` functions could also be useful. There's currently a `sumBy` function in Remeda, so `R.sum` could be as simple as `R.sumBy(R.identity)`.

**Comment by LandonSchropp** [comment]
If you like this idea, I'm happy to open a PR. 🙂

**Comment by eranhirsch** [comment]
@TkDodo, I know these are added as examples in our mapping.Md file, but I personally feel it's OK to have them implemented as functions (similar to how 'prop' is helpful when it's similarly simple as an arrow function: `({ [prop]: value }) => value`

**Comment by LandonSchropp** [comment]
For context, this fell out of some of my Advent of code answer this year. I found myself repeating this a lot:

``` typescript
return result.reduce((sum, number) => sum + number, 0);
```

I liked the idea of `add` as a utility function because I thought it made the code a bit more readable.

``` typescript
return result.reduce(R.add);
```

`sumBy` was an option that I used as well with `R.identity`:

``` typescript
return R.sumBy(result, R.identity);
```

However, it seems `R.sum` would be a bit tidier. (`sumBy` could be thought of as a composition of `map` and `sum` in this context.)

``` typescript
return R.sum(result);
```

I'm happy to close this if you'd like—just thought I'd suggest it. What do you think?

**Comment by LandonSchropp** [comment]
@eranhirsch Sounds great! I'll try to get those over to you in the next few days.

**Comment by LandonSchropp** [comment]
> I personally feel it's OK to have them implemented as functions

Apologies, I read that wrong the first time. For some reason, I thought you wrote that you didn't feel that it was OK to have them implemented as functions. 😬

**Comment by LandonSchropp** [comment]
@eranhirsch Hey, did you see [this draft PR](https://github.com/remeda/remeda/pull/443) I opened? No worries if you're busy hand haven't had a chance to look—I just wanted to make sure you didn't miss it. 🙂

**Comment by eranhirsch** [comment]
Your comments sounded like you were planning to continue working on it, and I usually don't go over draft PRs. Is there a reason you are keeping the PR in draft?

**Comment by LandonSchropp** [comment]
Oh, I just wanted to make sure you were good with the approach before I did the rest of them.
