### ISSUE TITLE
Add function to get a random item from array

### ISSUE THREAD

**Issue by gustavopch** [remeda/remeda#453]
Basically a shortcut to `R.shuffle(array)[0]`. Radash calls it [`draw()`](https://radash-docs.vercel.app/docs/random/draw), but  `randomItem()` is also good IMHO.

**Comment by eranhirsch** [comment]
Hey, we have `R.sample`. It returns an array because it supports more complex cases where you'd want to draw more than one item, but could easily be composed with `R.first` to get what you want.

```ts
const x = R.first(R.sample(data, 1));

// or even
const [x] = R.sample(data, 1);

// and even works in pipes:
const x = pipe(
  data,
  R.sample(1),
  R.first(),
);
```

**Comment by gustavopch** [comment]
Yeah, it's definitely possible already with `R.sample()` and `R.shuffle()`, just thought it's a common enough operation to deserve a shortcut, no?
