### ISSUE TITLE
Add isSymbol

### ISSUE THREAD

**Issue by viveleroi** [remeda/remeda#456]
We're hoping to replace lodash and ramda entirely with remeda. There are a few functions remeda doesn't have that I believe it could benefit from.

Remeda does not yet have `isSymbol` which we use from lodash. Admittedly `typeof value === 'symbol'` is probably enough to type narrow for most cases but it would fit nicely with the existing group of `is___` methods.

[Lodash docs](https://lodash.com/docs/4.17.15#isSymbol)
[Lodash source](https://github.com/lodash/lodash/blob/main/src/isSymbol.ts)

**Comment by eranhirsch** [comment]
Sounds great! can you send a PR?

**Comment by TkDodo** [comment]
fixed by #460
