### ISSUE TITLE
Filter types when using isArray break when data type is readonly

### ISSUE THREAD

**Issue by viveleroi** [remeda/remeda#459]
While experimenting with remeda over lodash I ran into an odd type error where an array I was filtering still allowed `undefined` in its return type. 

When filtering an array that holds arrays or undefined, the return types break when the array types are *readonly*.

In the following code I `filter` array `data` and the return type is `(readonly DateValue[] | undefined)[]` except undefined should have been filtered out because it doesn't match the `isArray` predicate.

This worked fine when using the `isArray` from lodash so after some digging I noticed that remeda's breaks when my array types are `ReadonlyArray`. Making the type `Array` solves the problem.

[TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAcigFMQSATZQgKBpIA9JY5gA7GEqbZAYxLgARZJwBqyADYBXAQG8acOFU4AuISJIK4AN0ky1bKSABGXGgF86vCG1TweAaxLCYyNRhLIKNiQE8AglBQyL4APC4k4tIkAHxwALxwANryiorKJAYkAO7qnAAUAJQANFqKutFqAIwWALpWNnZKIsgJyY7OLcVwUmwUJNjslN0dLsj1NNa29sASnKQUbcrIAHSDc1z5GCvAqIHBvoVAA)

```ts
import * as R from 'remeda'

export interface DateValue {
  date: Date
  value: number
}

const fakeData: ReadonlyArray<DateValue> = [{
    date: new Date(),
    value: 1
}]

const data = [fakeData, undefined, fakeData]

const filtered = data.filter(R.isArray) // (readonly DateValue[] | undefined)[] - but should be readonly DateValue[]
```

Replace `ReadonlyArray<DateValue>` with `Array<DateValue>` and the `filtered` type is correct

**Comment by eranhirsch** [comment]
Very interesting issue, i managed to fix it but I'm still not sure I can explain what is going on and why the fix works.

See #476
