### ISSUE TITLE
Support "ReadonlyArray" type in function arguments

### ISSUE THREAD

**Issue by vladimiry** [remeda/remeda#46]
I type arrays as readonly quite often and currently I have to make the array type writable when I use `remeda` functionality.

Code example:
```typescript
const props = ["prop1", "prop2"] as const;
// or similar:
// const props: ReadonlyArray<string> = ["prop1", "prop2"];
// const getProps = <T extends string>(props: readonly T[]) => props;

pick(someObject, props); // TS2345 compilation error
pick(someObject, [...props]); // works
```

It's, in general, a good thing to make all the function input args type-level/fake readonly/immutable since it reduces a chance you accidentally mutate the input args internally in the function implementation.

**Comment by lstkz** [comment]
Can you check 0.0.17? All functions should support readonly arrays.

**Comment by vladimiry** [comment]
Can confirm the issue is gone in v0.0.17. Thanks for the handy module!
