### ISSUE TITLE
Add `findSingle`

### ISSUE THREAD

**Issue by cjquines** [remeda/remeda#467]
A util I've written in several ways already: Return an element if and only if that element is the only one where the predicate is true, and undefined otherwise. `R.findSingle(items, fn)` would be equivalent to:
```ts
R.filter(items, fn).length === 1 ? R.find(items, fn) : undefined
```
but pipeable / with short-circuiting.

Example use cases:
* I have an array of command line options, which should contain exactly one of some list, and I want to show an error if there are none or more than one.
* I have an array that should have a single element I want to get: `R.findSingle(a, () => true)`.

**Comment by eranhirsch** [comment]
The Hack Standard Library has the `C\onlyx` function, which I often found useful when I worked at Meta. The `x` part in the name means it throws when the input was either empty or had more than one element, but a version that returns `undefined` makes more sense as you can always throw later using an invariant. It's a little broader and more generic than this request, but also useful in more cases.

I think it could be implemented lazily in Remeda using our current lazy architecture, but I'm not sure.

I'll be happy to review a PR that adds `only`
