### ISSUE TITLE
Add `mapWithFeedback` (aka scan, accumulate, partial_sum, runningReduce)

### ISSUE THREAD

**Issue by cjquines** [remeda/remeda#468]
This would be the equivalent of, say, [`scan` from Ramda](https://ramdajs.com/docs/#scan), [`itertools.accumulate` from Python](https://docs.python.org/3.11/library/itertools.html#itertools.accumulate), [`std::partial_sum` from C++](https://en.cppreference.com/w/cpp/algorithm/partial_sum), [`runningReduce` from Kotlin](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/running-reduce.html).

It would have a similar signature to `R.reduce`, but it would also be pipeable, like `R.map`.

Lots of room for bikeshedding the name.

**Comment by eranhirsch** [comment]
This sounds cool and useful. I think the clearest API for a function like this is to consider this a `mapWithFeedback`, basically a mapper that also takes the previous result (or the initial value on the first iteration). Looking at the Ramda code, I see that they also include the initial value in the returned array; I think we shouldn't do that to make the "mapping" concept clearer.

Do you want to send a PR for this?

**Comment by tbui17** [comment]
I'd be interested in taking a stab at this. Still trying to work out how _reduceLazy works with piping though.

**Comment by cjquines** [comment]
`_reduceLazy` "just works" with piping i think!

**Comment by tbui17** [comment]
I have a [PR](https://github.com/remeda/remeda/pull/517) for a working implementation for the common cases, but there's some edge cases and related bugs in other parts of the library that might require a larger scope of change.
