### ISSUE TITLE
In a pipe, even if the result of hasAtLeast is true, the return type is not Object, it is still boolean

### ISSUE THREAD

**Issue by Codfisher** [remeda/remeda#477]
I tried using the same examples as in the documentation for Data Last, but I keep encountering the error "Type 'boolean' must have a '[Symbol.iterator](https://chat.openai.com/c/a2f9fbd2-dd35-4093-8089-63a8d7425905)' method that returns an iterator" at the position of [first].

[TS Playground](https://www.typescriptlang.org/play?ssl=4&ssc=32&pln=4&pc=39#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAcigFMQSATZQgKBoGMIA7VeKmZALjiYFcQARiSgBtALpwAvHBEBGADRwATIoDMigCxiaGAHRhgYEgAp2yRXoAWaAIIwAMiTQxjsgJSLjI7MCisxblIAfDi+rG50QA)

![image](https://github.com/remeda/remeda/assets/16402070/e40d05a1-1775-4d23-ad70-d76011bc1f5e)

What might I have misunderstood?

**Comment by eranhirsch** [comment]
Sorry about that; the documentation is wrong. The value returned by `hasAtLeast` is a `boolean`, and not the array. It doesn't assert that the array is of length, it just checks it. I sent a PR with a better example.
