### ISSUE TITLE
Add `isNotNil`

### ISSUE THREAD

**Issue by lensbart** [remeda/remeda#495]
https://ramdajs.com/docs/#isNotNil

Happy to contribute, I guess in this case it can be a straightforward port from Ramda (the function only takes one argument)

Handy in combination with `filter`

**Comment by lensbart** [comment]
Thanks! `isDefined` is indeed exactly what I was looking for (and IMO better named than the Ramda equivalent).

Might be worth adding to the [mapping](https://github.com/remeda/remeda/blob/master/mapping.md) doc.

**Comment by eranhirsch** [comment]
Would you mind sending a PR for that?

**Comment by lensbart** [comment]
Consider it [done](https://github.com/remeda/remeda/pull/507)!
