### ISSUE TITLE
Type autocomplete on pick does not populate with 2+ keys when used in pipe

### ISSUE THREAD

**Issue by tbui17** [remeda/remeda#504]
Hello! I wasn't sure if these functions were meant to be piped, since the documentation on the hosted website did not label them as such but the readme uses pick in a pipe example.

Related: https://github.com/remeda/remeda/issues/408

# Reproduction
```typescript
type Data = { aProp: string; bProp: string };
const obj: Data = {
  aProp: 'p1',
  bProp: 'p2',
};
const result = pipe(obj, pick(['aProp', 'bProp']));
```
![Pasted image 20240210163808](https://github.com/remeda/remeda/assets/86227911/492da0b0-f58f-4b84-b1bc-1415b9a23347)

# Environment
Typescript Version: 5.3.2
[Sandbox (direct fork of repository)](https://codesandbox.io/p/devbox/3lj622?file=%2Fsrc%2Fpick.test.ts%3A81%2C21)

# Expected
The pick function, and similarly, omit, behave as expected when used alone and when used in pipe with one key provided, with full autocomplete support.
# Received
Autocomplete fields are not populated for any additional keys after the first when used in a pipe. 

# Suggested Fix
- The issue seems to be tangentially related to how the Typescript compiler struggles with contextual argument type inference with generics when overloads or currying are involved due to an inherent design limitation as suggested in the following issues: https://github.com/microsoft/TypeScript/issues/30369#issuecomment-476402214
https://github.com/microsoft/TypeScript/issues/46940
- Inverting the order of the overloads will allow autocompletion with multiple keys in a pipe. I am guessing that being able to [short-circuit](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#ordering) at the first match simplifies the compiler's overload resolution strategy.

![Pasted image 20240210163703](https://github.com/remeda/remeda/assets/86227911/42388213-e0b0-42ec-accd-ebda4cc786ff)

Please let me know if I may be missing anything. I am willing to make a PR to make any needed changes or update docs.

**Comment by TkDodo** [comment]
Can you make a PR with those changes and maybe add a type test? Then we can see if we're missing something :)
