### ISSUE TITLE
Was surprised this usage is not possible

### ISSUE THREAD

**Issue by thelinuxlich** [remeda/remeda#516]
![image](https://github.com/remeda/remeda/assets/5043/a0933e6d-2b89-47b2-b75a-ac2c0a8b93f9)

**Comment by eranhirsch** [comment]
Running multiple async functions concurrently is not trivial in javascript and adds additional complexity to utilities. From my experience, it's better to consider how you run concurrency as part of a pipe where the async part is explicit.

```ts
const data = pipe(
  await pipe(
    documents,
    map(async ({ document_id, type }) => ...),
    async ($) => await Promise.all($),
  ),
  flatten(),
  fromPairs.strict(),
);
```
