### ISSUE TITLE
`mergeDeep` does not allow interface types

### ISSUE THREAD

**Issue by RedHatter** [remeda/remeda#522]
`mergeDeep` does not allow interface types. The following

```
interface Example {
  b: string
}

const a: Example = { b: 'c' }

R.mergeDeep(a, { d: 'e' })
```
fails with
```
Argument of type 'Example' is not assignable to parameter of type 'Record<string, unknown>'.
  Index signature for type 'string' is missing in type 'Example'.
```

**Comment by cjquines** [comment]
i think this is microsoft/typescript#42825—interfaces are a target for declaration merging and so can't extend `Record<string, unknown>`

**Comment by eranhirsch** [comment]
I can see if we can extend the types to support interfaces, too; regardless, take a look at the following explanation of what kind of challenges `mergeDeep` introduces (here, about Classes):

https://github.com/remeda/remeda/pull/317#issuecomment-1937495183

**Comment by Bessonov** [comment]
Run in the same issue. I didn't look deeper, but wondering if `Destination extends object, Source extends object` miss some cases.
