### ISSUE TITLE
Should predicates be allowed to return null / undefined?

### ISSUE THREAD

**Issue by joshuahhh** [remeda/remeda#523]
Hi! I just ran into a spot where I wanted to type:
```
R.filter(id => builds[id].result?.ok)
```
However, the use of optional chaining (`?.`) here presents a problem, as an `undefined` or `null` in `builds[id].result` will result in the function returning `undefined` or `null`, and `R.filter` wants a predicate that returns a boolean.

My use of optional chaining in a condition here is quite idiomatic – the [TypeScript release notes on optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) shows an example of its use in an `if` statement. So it seems harmless & helpful to use a `Pred<T, boolean | null | undefined>` type here rather than `Pred<T, boolean>`.

Then again, there's nothing preventing me from typing:
```
R.filter(id => builds[id].result?.ok || false)
```
It's just a bit more clutter.

Curious what you think of this! Thanks.

**Comment by eranhirsch** [comment]
In addition to Remeda being a runtime library of utilities, Remeda is also a types library that ensures that the types are as strict as possible. This allows us to shift many of the common errors and bugs you'd find in Lodash and Ramda (that are runtime-only) from the run time to the compile time (e.g. as typescript errors). This allows you to catch the errors before they reach production servers and appear on logs.

By accepting narrow types, we ensure that your assumptions/contract when calling a Remeda function stay valid/accurate even in face of upstream changes.

The issue you raise comes up often as feedback about guards. The example I usually give is this: you have a function foo that returns an array with results (like a search function maybe). The function doesn't return `undefined` as that is meaningless for it. Someone else then wants to wrap that function and return some other results when the results are empty:
```ts
const result = foo();
return hasAtLeast(result, 1) ? result : DEFAULT_RESULT;
```

If hasAtLeast would accept `undefined` as a valid data value, and will assume that `undefined` should be treated as an empty array, we would return `DEFAULT_RESULT` for 2 cases now, `undefined` results, and `[]`. But if those cases don't have similar semantics, and if one of them is actually an error, you would never get notified about it and only detect it when it blows up in prod. By forcing `hasAtLeast` to accept **only** arrays, we can make sure that when `foo` is changed to return `undefined`, **the person who introduced that change** causes a type error and needs to consider their change in all downstream consumers.

```ts
const result = foo();
invariant(result !== undefined, "User isn't authorized to access API");
return hasAtLeast(result, 1) ? result : DEFAULT_RESULT;
```

Similarly, the filter has one semantic purpose: the predicate should tell whether the item should be kept or discarded. If the predicate can return a 3rd value, which isn't either yes or no, that change in the semantics of the data needs to be considered explicitly for this call site.

As you mentioned, it's usually straightforward to fix it by coalescing with the correct "fallback" value, depending on your specific semantics (and it isn't always `false`, e.g. `(response) => response.isSuccess ?? true // isSuccess was added recently, not all responses have it`)
