### ISSUE TITLE
`partition` does not narrow down the types

### ISSUE THREAD

**Issue by snax4a** [remeda/remeda#529]
Hello,

I am trying to partition an array by the optional field existence, but it looks like the types are not being narrowed correctly.

```typescript
interface Item {
  id?: string;
  name: string;
}

const items: Item[] = [{ id: "1", name: "a" }, { name: "b" }];
const [withId, withoutId] = partition(items, (x) => isDefined(x.id));
```

I would expect that `withId` would infer as `{ id: string, name: string }`, while `withoutId` as `{ name: string }`
But currently both arrays are of type `Item[]`.

https://codesandbox.io/p/sandbox/typescript-playground-export-forked-kfkk6f?file=%2Findex.ts

TypeScript version: `5.3.3`
Remeda version: `1.4.4`

Do you think it could be possible?

**Comment by cjquines** [comment]
related to #461 i think

using `hasProp("id")` would [correctly narrow `withId`, but not `withoutId`](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZVGANsAZgTzgXziyghDgHIYcwBTAWixoGcZyBuAKDWniTAENYwGMAgA7AkRJkARFBogaAE34zOHKrTgBBMTgBq-TEoDyAIwBWNAMYwA0jTwBeOCyjAxAczgAfOGIBXEDMaKF9XHGCIdE5NGjgAcRoxUOBrcytbOBcAJRtoJQAeXQMjYFNLG3tHABo4ALEAazEIAHcxAD51OJ10dABVMVExBxwmQsHhjuy4SfE4GgAPGGSlJlmh+YB+OEbHCCwN4bgALn8aADdQ7up4gFExJgD5O+XV8YAVOv7pl36Ft5iNZwD5wHb-M6ocCYXCFUEAMlmXQ4GlucAAsvw9qM8gBHALAeRFDJ1AAKJDAAJWQPWexwBzgGV+jJAwkKJLg5IgYGmiIQHDgcAA2nS4B5ORSALp0LZnV7WdABJQ0dmWEWOSV1BrKrAeZTI-A3LRzMTohQ0EJQJgAdWEAAsuWBVRYyRSqe9dvtDkyZq8YFB+LZCgLGZYaiGkOq8OLHZLZXB+HoCBxkaitLaYHa8QSiY7na7ue6ab0BpsRo5xkzmVCMNgcMHBZjsY5s4TlBMy2bFJabfa8xzHR0CzyU+osA1bMc7fwmHmQxki8Ckil3OlKrZw4LHYv1to+ibRpXLEOUwAKEN0s6OjgASjOp4gljOGRv2Wmj4sYvWDyeL0Ba3zOAMyzGh8TbJR+zDCVuQ6VMegASRWMgXH5QVynjNwPE8ThBTEfhFDOTCvE4Q0UWscQWDFJCmDORCFCFSUZiFJByjOGQAEYZDqPCCLgGRVAIOokB4mg2LMGQCElThyMeeAhVae14KUOoFMzCAAhgJTGJcAQhBEcRT2EBQmDqadZwpU8ZHKGQbxvdRVLtJTOAAemcuAAD0thRBz1M0pQXLczygA)... not sure if there's a way for `withoutId` to be typed correctly though

**Comment by eranhirsch** [comment]
In general, notice that the type of `(x) => R.isDefined(x)` would be `boolean`. This is a typescript limitation, calling a type-predicate (a function that narrows a type by returning `is ....`) in an naked arrow function (that does not define the return type explicitly) does not "carry over" the type-predicate nature of the function to the new function, typescript does not infer an `is ...` return type automatically, it has to be done manually.

**Comment by snax4a** [comment]
Thank you
