### ISSUE TITLE
TSDoc comments are removed in built d.ts files and cannot be referred to when imported as a package.

### ISSUE THREAD

**Issue by somnicattus** [remeda/remeda#533]
There seems to be rich tsdoc comments in the source files, but no tsdoc comments can be referred to from the built package, because `removeComments` in `tsconfig.build.json` is enabled.

The online references are very elegant, but in-editor reference comments will be also very helpful.

Is it intentional? I would be happy to publish a pull request to solve the problem.

**Comment by eranhirsch** [comment]
@TkDodo removed them a while ago before I joined the project so I don't have context as to why...

**Comment by somnicattus** [comment]
I am also wondering why declaration maps are generated but source maps are not...

**Comment by somnicattus** [comment]
Here's a [PR](https://github.com/remeda/remeda/pull/534).

I hope it will solve the problem.

**Comment by somnicattus** [comment]
Here's [another version](https://github.com/remeda/remeda/pull/535).
