### ISSUE TITLE
Any option to change `category: Array` for equals?

### ISSUE THREAD

**Issue by chmac** [remeda/remeda#55]
Just looked at the source for the equals() function because:

* I didn't click the "expand arguments" in the docs
* I read the `Array` in the docs and wasn't sure if it would also apply to objects

It seems like functions can only belong to a single category. Would `Object` make more sense? I'm not really sure. I'd think maybe folks assume that an `Array` is also an `Object`, but maybe `Object` is just as unclear as `Array`.

If you've already considered this issue and decided on `Array`, feel free to close this issue without comment. Thanks again for remeda, really nice to have typescript native util functions.

**Comment by lstkz** [comment]
Thanks for catching it. It's fixed now.
