### ISSUE TITLE
Allow `undefined`, `null` as parameters to mergeDeep

### ISSUE THREAD

**Issue by bombillazo** [remeda/remeda#552]
Currently, we use the fantastic `mergeDeep` function. Still, we constantly have to default its value to an empty object if any of the incoming parameters are not defined or null, like so:
```ts
R.mergeDeep(destination || {}, source || {});
```
It is common when dealing with database objects that values are nullable, and many times one can try to merge with a potentially undefined object at some point. It would be awesome if this function natively handled those cases.

**Comment by bombillazo** [comment]
On the typing side, I would expect that if one of them is nil, the returned type is the one not nil. If both are nil then perhaps undefined is returned.

**Comment by bombillazo** [comment]
I tried something like this but TS doesnt like this
```ts
export const _merge = <
  Destination extends Record<string, unknown> | undefined | null,
  Source extends Record<string, unknown> | undefined | null,
  Result = Destination extends undefined | null
    ? Source extends undefined | null
      ? Record<string, never>
      : NonNullable<Source>
    : Source extends undefined | null
      ? NonNullable<Destination>
      : MergeDeep<Destination, Source>,
>(
  destination: Destination,
  source: Source,
): Result => {
  if (!destination && source) return source;
  if (!source && destination) return destination;
  if (source && destination) return mergeDeep(destination, source);
  return {};
};

```
```sh
Result could be instantiated with an arbitrary type which could be unrelated to NonNullable .
```

**Comment by TkDodo** [comment]
We discussed allowing null / undefined as input but decided against it, as you might not want a default behavior (but rather a type error) when you change one input from being an object to being potentially undefined. With the current types, the call-sides need to make sure to handle these cases explicitly. Yes it's a bit more code in user-land but it's the safer thing to do.
