### ISSUE TITLE
Add type safe `curry` function

### ISSUE THREAD

**Issue by somnicattus** [remeda/remeda#561]
Related to #560.

I finally found that curry is enough for most users. This worked well with generic-typed functions.

```ts
export type Curried<
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    F extends (...args: readonly any[]) => unknown,
> =
    Parameters<F> extends readonly [infer T, ...infer R extends unknown[]]
        ? (...args: R) => (arg: T) => ReturnType<F>
        : never;

export type NthCurried<
    N extends number,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    F extends (...args: readonly any[]) => unknown,
    A extends unknown[] = [unknown],
> =
    Parameters<F> extends readonly [unknown, ...unknown[]]
        ? A['length'] extends N
            ? Curried<F>
            : NthCurried<N, Curried<F>, [unknown, ...A]>
        : never;

/**
 * Curry a function's parameter.
 *
 * @example
 * const pow = curry(Math.pow);
 * const result1 = Math.pow(2, 3); // 8
 * const result2 = pow(3)(2); // 8
 *
 * @example
 * const map = <I, O>(
 *     ...args: Parameters<Curried<typeof _map<I, O>>>
 * ): ReturnType<Curried<typeof _map<I, O>>> => curry(_map<I, O>)(...args);
 * const result1 = _map([1, 2], x => x * 2); // [2, 4]
 * const result2 = map((x: number) => x * 2)([1, 2]); // [2, 4]
 */
export function curry<
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    F extends (...args: readonly any[]) => unknown,
    N extends number | undefined,
>(fn: F, nth?: N): NthCurried<N extends number ? N : 1, F> {
    const curried = ((...args) =>
        (a0: Parameters<F>[0]) =>
            fn(a0, ...args)) as Curried<F>;

    return (nth === undefined || nth === 1 ? curried : curry(curried, nth - 1)) as NthCurried<
        N extends number ? N : 1,
        F
    >;
}
```

**Comment by cjquines** [comment]
see also #458

**Comment by eranhirsch** [comment]
This still requires the user to use a lot of manual typing that can't be inferred. I tried using it with this example and got typing issues.

```ts
const mapped = pipe(
  ['a', 'aa', 'aaa'],
  curry(map, (x) => x.length),
);
```

The main use for currying is to get inference from Typescript automatically in pipes and as functors. If typing needs to be done manually, it just doesn't provide a lot of additional value over the existing solution.

I do think there's room for a `curry` function that could be used in pipes to adapt functions that are not dataLast to the pipe (like my example above), but currently the best solution for that would be:

```ts
const mapped = pipe(
  ['a', 'aa', 'aaa'],
  ($) => map($, (x) => x.length),
);
```

which is typed correctly and doesn't require any manual typing.

**Comment by somnicattus** [comment]
I finally made it with `nth` support!

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzmYYCmcC+cBmUIhwBEUaIaAJgIZEDcAUPQPQBULcAClVFeTGlADOcGAE90cAO4ALNADsRsuAHNgAN3m4ArnIDGMYBAViJwYbq1QowSnBZN6aAB6RYI8RgDCl65S48+AUEAHno4cLgmJjg0QQAbYDkYAFoKMyoAIzi0ZLlnFIS8uAABE1jdazAU2MKYJjkIZOcwBN1gFKo5UTCIgDEYp345CmEACgA6Se5lQQAuOFIqCiM40ThO0QBtAF0ASjgAXgA+OB0AawbJOQAaehODzm5eNH4hYN6T-PkRhbQllbWm3OlxucEm40SOAEcAASgMhj9gRArjttnAAPywuDzPIaKAMZhsWEvSxyAAqHiksmMSlUGgUOB0+kMxkpZjgFisNgodgczWg8DKcG8XMoMJJUHJHlCEUi0RqiRSaUEmWyuXyyUKGFKHkEFVQ1XiivqjWarXayQ2PXC-S+wzG4Omc1+-zkqzgm0dXVR+2OpzkF2RNzuh2tjwCLyC70+g2+wkWyzdgMh0LJ139gau6fBSJR222YdlmNGaiocS0aHmZN9J3FMFJFPQ0cLERxaDxBP5biFIt8FBlESiMSNSVS6SyOTyg01iW1ZT1lUNtRNTRc5o6XTDttj9rgEymUBm8wTAI9Xq2+ZrGZBt3ue8dh+dve5-merxCHyvz7FEqlTY+BKsOwr6BEI7gSDImgwLS6iaIyegGEY4EYOynJ9ryjguAKyFwAActB34UCBkZvGGuHwnGcByFoIAZAItyykOCqjsqqqThqWolPO+pVE0I51A0q4tMAbQbt0srbgiDoHkeLqJu6Gw7FeubBrKACCFG7ipOyHB62y3qGsrEe+0aaT8J5Jh6KnZpMKZQFidqIgGIKoi24SYmpmwAOTZHIyjQV5aKOcIuFubKGKwmFsrzPh0iEcZUa4emhHRumQLOUGNnjGp2xHGFbYdowQHEvWkqNhgkE0hgdJwUyiGsqY5g+NyGFdoKlKxYRdYNtKZFmcI1G0fRYZMfxY4qhO6rTpxOroAuBp8cuglmiJFpWhJ-X3jJzoWe6npTN6l6HCc1lhhpwXXkGOkPDsBkHGGCVvB8m27cmchQvZaaXVmYKTNp+ZhR53m+f50iBZtoXhVDEUlmWFZVle3VldKHxRa2e6luWlZwNWx14QRzU-qVf5oMESXCoT-YfGl1m-dluX5VR7YCJ2WHdh1BOiv2fUXYNdFQAxg7ymNrGTVOBSzlxuo8UuxrLWuq1iVum37uMTrHn88mAuePp46dd6q+r+NxZTj0hOTn5451lNIyTZPpgBRVsGE7C9msVDaAhLJecIYBPKB4wuy7JTOLwLRoMHuhGII8CQJI8wpWUEA4HAACyVDQeMccGw+MxXmhoijOnmdx1lTq7AwdgctH8CkIIWhxDAACMunF9IWfIqMABM6YAMwV3KcAAByRzXvz143Xe6XHoz993A9DiPdjB8UofgNko9yDHcAgFQYC6cEACS6YAPJHKMweyrnT6m-7JEhEnKcAPq72AR+n0cRwMewuwJzbv7lWCI-OAL897vzgGfe4JwC6jFAW-Y+ECv503LpXdgUct611iA3Zuuk4GjE2E3dMXd9JwCcHjMh7Au4L2iJsHucAAAsBYq7oO3nXbBU8Hiv1GKMJwOIaL8yvBQuAVD8GEOEXsWgg9aHpkYS7PkbN4DwWZEhAuA5wijVqONNiU0JZFFmuURci05amgVqJS0m4NoXUNo+DWro9obDLodPYesMpZh5juH4fNoQAB9-QUDQDgWcFBbyjBwHIeYvR0xJGkOiGKv9jYpXIrzfh0JMTkXmGI56CARrC00aLNU4sZx6O4oY5iAlGg6BVFCS0ghBDAGUHIcgSR0z6PmrxMpK4VpmPWhEFh8A0LcnmBsXS3Dr41jCtwqgAAGeYZtoybCmc4v0YTRjTLLo+XY+wqDCC6gAlGRwtk7MptGAkjFcmKi0WLDiktWkyyMUkFclSqDVNIMTFpJSFodPlsJbpFiIivNJFRaChwDgPB0P4wJeQeTeN8dEkFDwW6YgGbYeYowYHIuCUC6QcBkhwCboc9YXQK70EwIweg-jdBxG4BgJR9Ud5gK+jCc+7QyC2K1jjW69KwDoCgKillIAEZ4xhPEmEOwCR9K5egCgLcHgoHQBfdR0Q4AAD10Q9E2EQGg6ZNVauIFQfVRB9I9Bga-XY3CnCCPGCDaCuxBZDmhuEVV9BiX0Ala-KVHDkCoDQAqweKq1XhA1bqnVRBtX6poEa8IowAAkV4uHRvTDwy11rpC2p6Pah1EQnXEqAA

**Comment by cjquines** [comment]
hm, that still doesn't deal with [the previous example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbziAhmANHMwwFM4C+cAZlBCHAERS4i4AmKlA3AFCu4AekscMAnnjgBhAK5QowBgB5WceXAD0iuLgDOAG2AA7GAFp6wNSgBGG3Hu1d9Wq3AACAvGoDGksPvW2Yi7RD1cYFouwPoo2vxyCgBiqpwwuNr0anAAFAB0mShQAOZqAFxwNCj0ENoa-HDh-ADaALoAlHAAvAB8cKLaANZ+AO7a6KztzVHyAArZKHQJUGrS0e3WiclFuCVlFXA1OsS4UHAAKpiZ6Tt7cABKcQlJKZ09EP31daMK8gD8aSfZeYUXTW00j9CgcAe0LrgYOJtAdBLh5q1Xm9ClYAG57NgcbjQeBOfAAORgAAsxBIpPRZG98ddliltKIQCY9oM3spVJodPpDMYzBYrPE9LZ8I44a53J4ObpfP5AsFQnpqq9Yktbl8srkCqt1uVKtV6mCOt0+gNXgBBGmq+7G+otLZWx7aOqDYavCZQKaQvZzBYWlbFUo6u1Gh3HTL2p51F5vN6fU01ADk5m0OWJ8bqvpS+KR0Y+InEkhkC2zOcKhJJ+fJ0nxmFJBYpC0wNXDAzgJ1NdUROfkKNw6KgmMUACpB3JB3mJLqSJ0XDBgGV4ykwJNpnt0qPRw4uFMgrgNy4ymp4JBeraXPn+KkALIoYnpY8NNhwMf77SH1ZqUQaGAARlt19vx6pAATJgADMD5KCoAAce4HvANAfl+QG2oB4HARBbIwU+G72Fu4DmLBr7wKgYC2tIACSmAAPKtKkG5vN8GqFG6HozHMtaVniEDEHAAD6JEUdRrTCRuDR-JC0Kwng0gcTIXE8fxaCCXANHCS07RnhOqSKWAyk0Q0GTqnkD6EW+CGfj+to6akNTfpgQFOnAnDqU5T5wEBGEqDUIFwAALFGz5we+FnIc0yBoKkqScCiDJMlABrOWOHk2XZ7mNMwkFbD5-mjooWI8PAxDTrOZRwJpUD8JSChsl4nIGEYpjmJY1iCjowp4mKOASt40oBNwcphBESoZmq6Q-Jq-obLqET6i5zYsgo1Iqis9KMucAA+hr0LgxBtfQzqpMQ2iFNEmC6ES7ylmJcBlrJFJLfEtJwKtcVwJ81KFKlPoIK8L5vuV5K2pFjHGepxZAgADMxy6erMCI1BDjRg120ZHakKAQ6GY0ag0TQoCkd0Ipibw0FCUDaGk50tM0YWdNtu1WPQcDrZtVM02Fv6fADDBwIU5UXtz+3PcScB6HA3641UmbEoT4MPTcK2xec728+LC05tErytGwBDsH9xFoHg9C-mF2B4HR8hsnAAB67xRDUlBMJgjtO1QKDu5QTpRPzqQkQZUUJekSYpkSDQLVbKO26wD5AA)

```ts
const mapped = pipe(
  ['a', 'aa', 'aaa'],
  curry(map)((x) => x.length),
);
```

**Comment by somnicattus** [comment]
@cjquines It requires type parameters. 
```ts
const mapped = pipe(
  ['a', 'aa', 'aaa'],
  curry(map<string, number>)((x) => x.length),
);
```

**Comment by cjquines** [comment]
ah... i think this goes against the remeda philosophy though, which is to not have type annotations if possible...

**Comment by eranhirsch** [comment]
We can merge this with #234
