### ISSUE TITLE
FR: `get` accepting deep paths into objects.

### ISSUE THREAD

**Issue by jasikpark** [remeda/remeda#586]
I would like to use remeda, but an crucial functionality of lodash is the ability for `get` to access deeply nested properties in a single function call, ex: `get('a.b.c', { a: { b: { c: 123 } } })`. 

Remeda's `prop` is type-safe but only allows accessing one level deep, I'd appreciate it if y'all supported a `propDeep` that provided the above functionality, if that's possible.

Thanks for the solid work on a truly tree-shakable TS-first library!

**Comment by cjquines** [comment]
does `pathOr` solve this?

**Comment by jasikpark** [comment]
I'd believe so

**Comment by cjquines** [comment]
if it works, i'm going to close this issue @jasikpark ?

**Comment by cjquines** [comment]
is this a #355 duplicate, then?

**Comment by jasikpark** [comment]
I suppose with the fact that `stringToPath` exists, then yes? https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzmAhjAFgeSgGjgZximADsBzAFQgAU104BfOAMyghDgCIoBTEHgCYpOAbgBQYgMYQShOAA84AXkRwUALlUAjTUkmaA5OhTH0BtfjjTZ8JnfFSZcgJ7LkdbAAp5eQsXJUtBieBigAdFphkgYAlHgGJBDwzBAAriQCseIA9Nlw+XAAegD8ErlwAJJwAO4olrUkMKRkcBjAlqQwPFDMKJI86mKgkLCqZDy2LGwcnAA2EEL46KIS1nIAXm7jMN7x4ZHRMTl5BSVAA

**Comment by cjquines** [comment]
yeah, it seems like this is about the typing of the default argument, and how it should be able to not match the value at the path—we're already discussing this in the other pathOr tickets, so i'll close this one
