### ISSUE TITLE
`mapKeys`, `mapValues`, `entries`, etc. drop symbol keys without excluding them in the return type

### ISSUE THREAD

**Issue by russelldavis** [remeda/remeda#593]
Example:

```ts
const bar: Record<symbol, number> = {[Symbol()]: 42}
const baz = R.mapKeys(bar, (x) => x)
// bar and baz have the same type, but at runtime baz is empty
```

Note: in v1.x, the return type of `mapValues` excludes symbol keys, but I noticed in the beta branch it no longer does this.

**Comment by eranhirsch** [comment]
Thanks, this is a good observation. I'll take a look. We might just opt to drop symbols from our types...

**Comment by eranhirsch** [comment]
@russelldavis - Can you go over #600  (at least the tests for the relevant functions) and see that we now handle symbols as you'd expect?

**Comment by cjquines** [comment]
i'm gonna close this issue as it's released on beta—i don't think we can backport this change
