### ISSUE TITLE
Incorrect type assertion for isIncludedIn

### ISSUE THREAD

**Issue by JohanAlteruna** [remeda/remeda#614]
I noticed that the the `isIncludedIn` function, being an assertion function, behaves unexpectedly in the negative case when using a wide type for the `container` argument. Consider the following code:

```typescript
const x = "foo"; // typed as "foo"
const myArray = ["bar"]; // typed as string[]; TS default behavior unless `as const` is used
if (isIncludedIn(x, myArray)) {
	// x is typed as "foo" here; makes sense since it's "foo" & string
} else {
	// x is typed as never here; does not make sense because myArray does 
        // not contain every value of type string
}
```

Clearly this behavior does not reflect reality, but this code will compile. I suspect the error is the assertion function signature stating that `data is S`. If the function returns true, `data` can indeed be typed as `S`. But if the function returns false, it is not true that `data` cannot be typed as `S`. I don't have a good solution for this, but wanted to highlight this problem. Maybe something could be stated in the documentation about using this function when using a wide type for the `container` argument.

**Comment by cjquines** [comment]
hm, but isn't the `isIncludedIn` call [already a type error](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIigFMQSATZQgbgCg6MA6YVASQDsBjAGwFcKlTgAo6cItggRCKdFwgdUMADRi4AbUIAjZFEIBdWXCVRgHAObr9qgJRA)?

**Comment by eranhirsch** [comment]
`isIncludedIn` was recently updated (twice!). Can you validate that you are using the latest version of Remeda and add a playground link showing the issue you are reporting so we can pinpoint the exact behavior?

From the description it looks like things that have been addressed concretely in our latest changes, so it's unlikely that what you are describing slipped through, but typing is **hard** so there's always edge-cases.

**Comment by JohanAlteruna** [comment]
I will verify this on the latest version; should have checked before posting this

**Comment by JohanAlteruna** [comment]
Assuming the playground uses the latest version, this has now been fixed (thanks!): here is a [demonstration](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIigFMQSATZQgbgCg6BjCAO1XgA84BeI7CCLTgB6YXBgBPMJRTpC-QU1bs4ICQEEoUZBJ5wA2oQBGyKIQC6NEWMnSKsuOyjAWAc32W4AFQDKcCiTYyACuADbwRiQAFsgAbsDQcMEsoSSo6AAGaHDMbDAZcMDowaiUDKJwAOrQANboAPIA0nAsEADudMDYcAAUGAB0RQCSLIyhwQEUIz0cADSqGlo6AJTLcADedACQFVxF4lIy2fIChHBRJKRWIMg1aY4kbCSOLozPwDAA5HIKZwBkjhgzjcdDgcA4dAAvnASKFShtQdZwQc7A4ToJ5sg4RBVLd7qUnoiIZCgA).

An interesting note around @cjquines comment is that a type error occurs if `"foo" as const` is inlined but not if its passed as a variable. See [this demo](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIigFMQSATZQgbgCg6BjCAO1XipmTgF4jsIEWnAD0I-oMJNW7OMxZdgLElF5wA2oQBGyKIQC6NUePZQlAc3X6GYuABUAFsHSNkAGzdwA7tADWqOgwAOmcASRZGNwBXCkpwgApOZAAaOVZFZSgASjpbAGUSMnQ3YF8SOBgnF3dPVAcIKLcKOC1ykgBHKOAAN3cSBUCQ1HDImLiWeMIBIRQXGRhU+QyVLKA). IMO this seems like a separate issue; feel free to close this one :smile:

**Comment by eranhirsch** [comment]
> An interesting note around @cjquines comment is that a type error occurs if "foo" as const is inlined but not if the value is passed as a variable. See [this demo](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIigFMQSATZQgbgCg6BjCAO1XipmTgF4jsIEWnAD0I-oMJNW7OMxZdgLElF5wA2oQBGyKIQC6NUePZQlAc3X6GYuABUAFsHSNkAGzdwA7tADWqOgwAOmcASRZGNwBXCkpwgApOZAAaOVZFZSgASjpbAGUSMnQ3YF8SOBgnF3dPVAcIKLcKOC1ykgBHKOAAN3cSBUCQ1HDImLiWeMIBIRQXGRhU+QyVLKA). IMO this seems like a separate issue;

Notice (by hovering over the function) that typescript widens the "foo" const to be of type string when used inside the function. When you call the function as `isIncludedIn("foo" as const, ...)` the type of the data (T) would be "foo".

This isn't a bug, it's just how typescript works, read more about it in https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters
