### ISSUE TITLE
[Feature Request]: Support Maps in isDeepEqual

### ISSUE THREAD

**Issue by BuuBux** [remeda/remeda#626]
Deprecated `equals` seems to have worked correctly with maps, I guess isDeepEqual as a successor should also support maps, for me it would be a really cool feature and essential.

**Comment by cjquines** [comment]
i agree it should—do you want to send in a PR?

**Comment by BuuBux** [comment]
I'll try to do my best but no promises

**Comment by eranhirsch** [comment]
btw you mention that `equals` worked with Maps, but I don't think it ever did. It would simply return `true` for any 2 maps provided to it: https://codesandbox.io/p/sandbox/empty-cache-3tnrzs

**Comment by BuuBux** [comment]
👏🏻 🎉

**Comment by BuuBux** [comment]
> btw you mention that `equals` worked with Maps, but I don't think it ever did. It would simply return `true` for any 2 maps provided to it: https://codesandbox.io/p/sandbox/empty-cache-3tnrzs

You were right, i was doing equal for both `MapA.get('a')` and `MapA` and if we select 1 element from Map it was working when we compare Map it was false positive
