### ISSUE TITLE
error TS7016: Could not find a declaration file for module 'remeda'. 

### ISSUE THREAD

**Issue by lukasz-lelinski-atos** [remeda/remeda#63]
Hi!

Just installed your library via npm in Angular 6 project, but when trying to import it in a file I get the compilation error:

```bash
error TS7016: Could not find a declaration file for module 'remeda'. 
<REMOVED_FOR_BREVITY>node_modules/remeda/dist/commonjs/index.js' implicitly has an 'any' type.

Try `npm install @types/remeda` if it exists or add a new declaration (.d.ts) file containing `declare module 'remeda';
```

Is it a bug or am I missing something? Angular 6 has a dependency on typescript@2.7.2 whereas you're using the newest compilator. Could that be the case?

**Comment by kldkv** [comment]
`import * as R from 'remeda'`

**Comment by lukasz-lelinski-atos** [comment]
@kldkv yes, this is how I imported it :)

**Comment by lstkz** [comment]
@lukasz-lelinski-atos Can you provide an example repo?

**Comment by lstkz** [comment]
Closing because of no response.
