### ISSUE TITLE
Typing issue when using `isDeepEqual` in `differenceWith` function

### ISSUE THREAD

**Issue by eemelipa** [remeda/remeda#641]
# Current Behavior

Doing the following results in typing issue for the `firstArray` object `Argument of type 'string[]' is not assignable to parameter of type 'readonly never[]'. Type 'string' is not assignable to type 'never'.ts(2345)`

```ts
import * as R from 'remeda'

const firstArray = ['a', 'b', 'c']
const secondArray = ['a', 'c', 'd']

const difference = R.differenceWith(firstArray, secondArray, R.isDeepEqual)
```

# Expected Behavior

It should be possible to directly use the `isDeepEqual` in the above use case and the types should be ok.

# Workaround

At least two workarounds exist:

1. Explicitly give types for the `differentWith`
    - `R.differenceWith<string, string>(firstArray, secondArray, R.isDeepEqual)`
2. Use some other comparator for the is equal
    - `R.differenceWith(firstArray, secondArray, (a, b) => a === b)`

# Related Information

This used to work in version 1.58.0 but it doesn't work anymore in 1.58.3. Changes done in https://github.com/remeda/remeda/issues/634 might have affected it.

**Comment by eranhirsch** [comment]
Thank you for reporting, I'll take a look
