### ISSUE TITLE
Why is fromKeys typed with Partial<>?

### ISSUE THREAD

**Issue by JeongJuhyeon** [remeda/remeda#645]
Just curious because it's pretty inconvenient but I'm sure you have a good reason.

**Comment by cjquines** [comment]
in the case that e.g. `T = Array<number>`, then the result object doesn't have _every_ number as keys; only some numbers

there should be a more exact type if you use a [more specific input type](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIigFMQSATZQgbgCg6BjCAO1XlPQF5MA6XfAGkSAT1QAKANoBGADRwATAF0U6ZmxjzgcLgD44wXjAgBlGFGAsA5uICUt+gHpHcV3AB6AfiA):

```ts
const result = R.fromKeys([1, 2] as const, i => i.toString());

result // has type { 1: string; 2: string; }
```

**Comment by eranhirsch** [comment]
As @cjquines said, if it wasn't partial this would lead to a runtime error:

```ts
const data = [] as ("cat" | "dog")[];
const result = fromKeys(data, (key) => `${key}_123`);

// `cat` doesn't exist on `result`, it would return `undefined` in runtime
// but would be typed `string` in your code. Calling `toUpperCase` on `undefined`
// would throw.
console.log(result.cat.toUpperCase());
```

**Comment by eranhirsch** [comment]
If there are nothing else we can do please close the issue.

**Comment by cloud-walker** [comment]
> As [@cjquines](https://github.com/cjquines) said, if it wasn't partial this would lead to a runtime error:
> 
> const data = [] as ("cat" | "dog")[];
> const result = fromKeys(data, (key) => `${key}_123`);
> 
> // `cat` doesn't exist on `result`, it would return `undefined` in runtime
> // but would be typed `string` in your code. Calling `toUpperCase` on `undefined`
> // would throw.
> console.log(result.cat.toUpperCase());

wait, what?

But in this code example you are using the `as` keyword to lie to typescript: of course you will have a runtime error, no?

**Comment by eranhirsch** [comment]
> But in this code example you are using the as keyword to lie to typescript: of course you will have a runtime error, no?

We aren't lying to TypeScript because the types are sound here, it's equivalent to:

```ts
const data: ("cat" | "dog")[] = [];
declare const data: ("cat" | "dog")[];
const result = fromKeys(data, (key) => ${key}_123);
```
