### ISSUE TITLE
`groupBy` has broken types

### ISSUE THREAD

**Issue by dartess** [remeda/remeda#654]
```ts
import * as R from 'remeda';

type AnimalKind = 'horse' | 'cat' | 'dog';
type Animal = { kind: AnimalKind }
const animals: Animal[] = [];

const { horse } = R.groupBy(animals, R.prop('kind'));
      // ^? const horse: [Animal, ...Animal[]]

console.log(horse.length); // Cannot read properties of undefined (reading 'length')
```

demo: https://playcode.io/1850060

No key is guaranteed, so maybe the result should be `Partial<Record<PropertyKey, NonEmptyArray<T>>>`? Approximately the same typing was added for `Object.groupBy` in TS 5.4.

**Comment by cjquines** [comment]
this is already fixed in the `beta` branch, and we're not planning to backport the fix because it's a breaking change

we should probably write a migration note for this @eranhirsch ; similar to the one we have for `mapKeys`

**Comment by eranhirsch** [comment]
The `strict` variant has the correct typings for groupBy. @dartess, have you tried using it?

**Comment by dartess** [comment]
@eranhirsch I just assign an empty array when destructuring, even though the types don't require that :)

@cjquines yeah types in beta looks good! It seems the issue can be closed.
