### ISSUE TITLE
Add `mapAccum`

### ISSUE THREAD

**Issue by ludwignagelhus** [remeda/remeda#674]
I can try create a PR for this if I get some help with the types.

These are the docs for Ramda's version: [mapAccum](https://ramdajs.com/docs/#mapAccum)

Should the data last version be the same as Ramda?

**Comment by cjquines** [comment]
you might be looking for https://remedajs.com/docs/#mapWithFeedback

**Comment by ludwignagelhus** [comment]
I'm looking for something like that, yes. Specifically I am looking for a function like `mapWithFeedback`/`mapAccum`, but for `Record<T, U>`.

**Comment by cjquines** [comment]
can you give an example of what that'd look like? i'm not sure what you mean here; `mapAccum` doesn't do that either

**Comment by ludwignagelhus** [comment]
In Haskell I think there is a implementation for this.

**Comment by cjquines** [comment]
i'm not sure i see the use of this... entries in an object don't have an order they appear in. (technically, the order they're enumerated is consistent, but i don't think that records should be treated as having an order; in that case you want an array)
