### ISSUE TITLE
Incorrect type assertion in negative case for hasSubObject 

### ISSUE THREAD

**Issue by JohanAlteruna** [remeda/remeda#678]
Hi, 
I noticed that `hasSubObject`, when used as a type guard, behaves unexpectedly in the negative case:

```typescript
import * as R from "remeda";

const superObject = { foo: 1, bar: 2 };
const subObject = { foo: 3 };

if(R.hasSubObject(superObject, subObject)) {
    superObject // correctly typed as { foo: number; bar: number; }
} else {
    superObject // typed as never; should probably be { foo: number; bar: number } as well
}
```

Clearly, in this example, `subObject` is not a sub-object of `superObject`, and so the negative case is a valid outcome of the check.

[TS playground link](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAIigFMQSATZQgbgCg6BjCAO1XlQFcwSoB5AEYArEo3gBeOAG8cECAC44ARgA0cAciiKATHAC+9Zmw6cBgkWLiSZ2OYoDM++nWDYAFBgB0ACzQBlU3NRGDcuHn5hYLUuM0ixAEp46To4VLgw3iDLAHpsuBgATx4KFHQbOzgWThABXhp1TUUqmrr9Oj04EgAbVBJktPTuTLj4XPyiylLKkgA3XnagA)

**Comment by eranhirsch** [comment]
This makes sense, thanks for reporting
