### ISSUE TITLE
Doc: groupBy is missing pipeable directive

### ISSUE THREAD

**Issue by jamesst20** [remeda/remeda#682]
https://remedajs.com/docs/#groupBy

There is literally an exemple

![Capture d’écran, le 2024-05-28 à 20 22 46](https://github.com/remeda/remeda/assets/490234/e9bb1183-eb18-491b-a7b8-5efb579a9d8a)

Same goes for this one actually: https://remedajs.com/docs/#entries

Maybe i'm missing something?

**Comment by eranhirsch** [comment]
Pipeable was the wrong name for the concept and would be renamed "lazy" in v2. groupBy and entries both don't have lazy implementations so both won't be tagged as lazy. Sorry for the confusion and thanks for reporting.

**Comment by jamesst20** [comment]
> Pipeable was the wrong name for the concept and would be renamed "lazy" in v2. groupBy and entries both don't have lazy implementations so both won't be tagged as lazy. Sorry for the confusion and thanks for reporting.

So there are not really any kind of indicators that tell you what can be used in pipe(...) or not right? Everything that supports data last and returns a value basically is capable of that. Ain't that right?

Maybe while I'm at it I can ask you if there are any methods in Remeda that mutates an object or if everything is actually by copy?

**Comment by cjquines** [comment]
yep, every data-last function can be used in a pipe, even ones you make your own

everything operates on shallow or deep copies of input data
