### ISSUE TITLE
v2 omitBy and pickBy typing change

### ISSUE THREAD

**Issue by paradoxloop** [remeda/remeda#696]
Migrating our app to v2 and noticed that the typings for pickBy and omitBy now return undefined as a potential type. There might be a good reason for this but I dont see how that could be possible at runtime.

Code to recreate:
```
type Deer = Record<string, { name: string; children: string[] }>;

const deerList: Deer = {
  john: { name: "john", children: [] },
  peter: { name: "peter", children: ["alice"] },
};

const y = pickBy(deerList, (v) => v.children.length === 0);

// type in v 2
// const y: {
//     [x: string]: {
//         name: string;
//         children: string[];
//     } | undefined;
// }

// type in v1
// const y: Deer
// or to make comparison easier
// const y: {
//     [x: string]: {
//         name: string;
//         children: string[];
//     }
// }
```

**Comment by cjquines** [comment]
seems like a bug to me, and yeah, i don't see how this is possible at runtime.

**Comment by eranhirsch** [comment]
Thanks for reporting! #706 fixes this.

**Comment by marbemac** [comment]
@eranhirsch @cjquines heads up it seems the issue still occurs if the record keys are template literals, like so (worked prior to v2):

<img width="590" alt="Screenshot 2024-06-06 at 1 04 28 PM" src="https://github.com/remeda/remeda/assets/847542/14ad665e-f24d-4a97-a7c1-bb3d5f56429e">

This is on remeda v2.0.5.

**Comment by cjquines** [comment]
@marbemac this is for the same reason as #719 , and should be fixed with the same thing—i'll make a note to add a test for it
