### ISSUE TITLE
firstBy: cannot read properties of undefined '0'

### ISSUE THREAD

**Issue by jvnm-dev** [remeda/remeda#709]
Codesandbox: https://codesandbox.io/p/sandbox/frosty-wozniak-hfpy29

I noticed that `firstBy` is not working anymore in v2 when combined with `identity`.

The `max` example is still the same in the documentation: https://remedajs.com/docs/#firstBy

**Comment by eranhirsch** [comment]
Sorry, the example was wrong; we no longer support "headless" invocation of identity; to fix this, you'd need to use `identity()`. I've shipped a fix to the docs.
