### ISSUE TITLE
Add "zipObj" function

### ISSUE THREAD

**Issue by dodas** [remeda/remeda#72]
Are we interested in `zipObj(keys, values)` function? I use it quite frequently and would like to have it in remeda.

If so, I can send an PR.

**Comment by jbpotonnier** [comment]
The `zip` and `zipWith` functions would be nice too.
Maybe add theses first.

Then add a function that goes the opposite direction than `toPairs`. 
I think it would be more consistent and composable.

**Comment by steevsachs** [comment]
Created the ingredients I think we need to get to `zipObj`.  If these PRs land, `zipObj` (I think just a pipe through `zip` (or `zipWith` for `zipObjWith`?) and then `fromPairs` should hopefully be pretty straightforward).

**Comment by eranhirsch** [comment]
Feels like this has been covered by other functions and the ability to build a pipe for it.
