### ISSUE TITLE
Sliding window function

### ISSUE THREAD

**Issue by antonkatz** [remeda/remeda#73]
I find myself needing this often:

```
function toWindows(inputArray, size) {
  return Array.from(
    {length: inputArray.length - (size - 1)}, //get the appropriate length
    (_, index) => inputArray.slice(index, index+size) //create the windows
  )
}
```

What does the community think about adding this functionality in?

**Comment by lstkz** [comment]
Does lodash or ramda have a similar function? What's an example use case for it?

**Comment by AprilArcus** [comment]
lodash has `chunk`

```
for (const chunk of _.chunk(array, 5)) { ... }
```

and Ramda has `splitEvery`:

```
for (const chunk of R.splitEvery(5, array)) { ... }
```

**Comment by philihp** [comment]
@lstkz apologies for being 2+ years late here, but perhaps [`aperture`](https://ramdajs.com/docs/#aperture) is what you're looking for?

**Comment by cjquines** [comment]
i think we should do this, it's tc39 stage 1 https://github.com/tc39/proposal-iterator-chunking
