### ISSUE TITLE
Pronunciation?

### ISSUE THREAD

**Issue by kabo** [remeda/remeda#731]
How do you pronounce `remeda`? RemEEda? Or is it like remedy?

**Comment by cjquines** [comment]
i pronounce it like remedy

**Comment by eranhirsch** [comment]
I pronounce it Re-MEE-da, I also have no idea what the origin of the name is so can't deduce from that...

**Comment by kabo** [comment]
I also pronounce it Re-MEE-da, but wasn't sure if that was right.

**Comment by cjquines** [comment]
i would believe it's derived from remedy… maybe because it's supposed to be a "remedy" to (insert other utility library)

**Comment by eranhirsch** [comment]
@lstkz, how do you pronounce it?

**Comment by lstkz** [comment]
https://translate.google.com/?sl=pl&tl=en&text=remeda&op=translate
Click listen on the left side (polish).
I believe it's something like Re-MEE-da.
It doesn't have any meaning, but it's just a similar word to remedy.
