### ISSUE TITLE
Type inference in generic functions with zip

### ISSUE THREAD

**Issue by HugeLetters** [remeda/remeda#741]
Here's a basic repro.
https://tsplay.dev/N5dDdw

Using zip in a generic function where a type parameter is the array itself(not array member) and then destructing zipped value results in a lost type inference.

Unless I'm misunderstanding something it should understand that the x has type `T[number]`

**Comment by cjquines** [comment]
`x` does have the type `T[number]`, which in this case is `unknown`

**Comment by HugeLetters** [comment]
@cjquines hmm, you mean it's just an issue similar to this one?
https://tsplay.dev/ND0bjN

so the solution would be to add an explicit return type?

**Comment by cjquines** [comment]
i believe so

**Comment by HugeLetters** [comment]
ok, thanks for clearing it up!
