### ISSUE TITLE
How to properly type pipeline inputs

### ISSUE THREAD

**Issue by HugeLetters** [remeda/remeda#744]
Say I have an example like this
```ts
  const pipeline = r.piped(
    r.zip([1, 2, 3]),
    r.map(([a, b]) => a + b),
  );
```
This gives a type error because `a`  has a type unknown

you can fix it with 
```ts
  const pipeline = r.piped(
    (x: Array<number>) => x,
    r.zip([1, 2, 3]),
    r.map(([a, b]) => a + b),
  );
```

is there a more idiomatic way you're supposed to do this?

**Comment by cjquines** [comment]
not really. this is duplicate #212 ; if you want something like this you should upvote that issue
