### ISSUE TITLE
setPath multiple props

### ISSUE THREAD

**Issue by stychu** [remeda/remeda#763]
How one would update multiple values of deep nested object with setPath or some other function ? Given that setPath return a new modified object and doesn't mutate the original one it's a bit tricky to me how to approach multiple values updates. Ideally it would do update in one pass rather than multiple.

```js
const state = {
  originalView: false,
  settings: {
    theme: 'light',
    notifications: true, 
	banner: {
		front: true,
 		back: false
     }
  }
};

```

let say I want to update the `banner.front` `banner.back` `theme` and `originalView`

**Comment by cjquines** [comment]
maybe `evolve`?

**Comment by stychu** [comment]
@cjquines  ahhh great. Thanks for suggestion. I was looking into it earlier but anyway missed to try. Works like a charm now.
