### ISSUE TITLE
Feature Request: setPath

### ISSUE THREAD

**Issue by chmac** [remeda/remeda#78]
It would be awesome to have an option to set values deeply nested with a path value. Ideally, something that supports lodash's format would be ideal, although I realise that might be complex to implement.

```javascript
var object = { 'a': [{ 'b': { 'c': 3 } }] };
 
var object2 = R.setPath(object, 'a[0].b.c', 4);

console.log(object2.a[0].b.c);
// => 4
```

If it's easier, or to keep in line with `R.pathOr` it might make sense to use an array for path instead.

``` javascript
var object3 = R.set(object, ['x', '0', 'y', 'z'], 5);

console.log(object3.x[0].y.z);
// => 5
```

**Comment by lstkz** [comment]
Would you be interested in creating a PR?
`setPath` can work similarly to `pathOr`.
We can't support string paths (`'a[0].b.c'`) because they are not typescript friendly.

**Comment by chmac** [comment]
@lstkz I just had a look at the source for `pathOr`. Oh wow! I think my typescript fu is not quite at the point where I can contribute. I struggle to understand the code in that file, never mind well enough to modify it to create a `setPath` variant. Maybe in the future I'll be better placed to support, but for now, I'm afraid this appears to be beyond my skills.

**Comment by TkDodo** [comment]
The string version can be made typesafe with the upcoming [Template literal types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#template-literal-types) in TS 4.1

**Comment by bennidhamma** [comment]
Why would I use `pathOr` instead of just doing something like `object?.a?.[0]?.b?.c ?? 5`

**Comment by chmac** [comment]
@bennidhamma Here we're talking about setting values, not getting them. Using conditional access like that a?.b?.c would mutate the object, while remeda makes all objects immutable.

**Comment by gothy** [comment]
This would be an awesome addition to the library 👍

**Comment by bombillazo** [comment]
What is remeda's equivalent to `unset` from lodash?
