### ISSUE TITLE
`isEmpty` may accept `undefined` value

### ISSUE THREAD

**Issue by RoyRao2333** [remeda/remeda#786]
<img width="1798" alt="image" src="https://github.com/user-attachments/assets/c8a297db-cc96-4b49-a341-922f4527924e">

<img width="764" alt="image" src="https://github.com/user-attachments/assets/4520e77d-6149-41ef-9771-63f0ece77f9f">

When the value is `object`, `undefined` and `null` is not allowed in typings.

**Comment by RoyRao2333** [comment]
I recently moved to this library and I love it.

Sorry if I misunderstand the design philosophy here, but lodash and radash supports checking for `undefined` or `null`, and it's really useful to me personally.

**Comment by eranhirsch** [comment]
Lodash and Ramda were written in JS and didn't have any design assumptions about using TypeScript. Remeda is a TypeScript-first library, and thus, it relies on certain things that are possible via the typing system to avoid adding code to the runtime.

This has been raised and discussed in https://github.com/remeda/remeda/issues/775
