### ISSUE TITLE
pickBy return type assumes predicate always returns true

### ISSUE THREAD

**Issue by erquhart** [remeda/remeda#791]
I would expect the return type of `pickBy()` to be a partial of the provided object. I see there is a condition in the source for this, but the return type seems to be always be the same as the provided object, not a partial. This may be intended behavior, but seems like a bug. Please let me know if I'm holding it wrong.

```ts
  const fooBar = { foo: true, bar: true }
  const foo = { foo: true }
  const change = pickBy(foo, (value, key) => {
    return fooBar[key] !== value
  })
  change.foo
  // expected: (property) foo?: boolean | undefined
  // actual: (property) foo: boolean
  ```

**Comment by eranhirsch** [comment]
Can you provide a typescript playground link reproducing this issue? This doesn't reproduce for me:

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzmYBjA1gIQJ5wL5wBmUEIcARFAKYhUAmAhuQNwBQrqEAdgM7yEQImBlDgBeREUEAuODCgBXKgBo4AIxGz5S-B258pEcZIEQtiqrs694qABYMuAc0sSUGHAApTqzwDcGABslVXQqbABKcQA+RFY4OGoYBSguQ2EoAG0w7ABdOABCMQkA4KpWPAj2e0cXADpTVgB6JoS2gD0AfiA

**Comment by erquhart** [comment]
Just realized I'm on v1, looks like this isn't an issue anymore 👍
