### ISSUE TITLE
Playground/REPL in docs

### ISSUE THREAD

**Issue by pavitra-infocusp** [remeda/remeda#810]
Lodash uses [Runkit Embed](https://runkit.com/home#embed) to provide a REPL directly in their docs. This is so useful to try out different functions.

I'm happy to contribute this feature.

**Comment by cjquines** [comment]
so note that we already support a repl if you open your browser console, and it'll be better than whatever repl we can provide through runkit or otherwise because it's in the browser console

with that said, is there still some use for this? or what is this pointing toward

**Comment by pavitra-infocusp** [comment]
I think that's great! Somehow I had no clue...
