### ISSUE TITLE
Data-last `map` inside `evolve` has unknown input type

### ISSUE THREAD

**Issue by stychu** [remeda/remeda#821]
```ts
const base = {
  someData: [
    { value: "1", disabled: false },
    { value: "2", disabled: false },
    { value: "3", disabled: false },
  ],
};

const result = R.pipe(
    base,
    R.evolve({
        someData: R.map((data)=>({...data, disabled:data.value === '1'}))
    })
);


const result2 = R.pipe(
    base,
    R.evolve({
        someData: (data) => R.map(data, (value)=>({...data, disabled:value.value === '1'}))
    })
);
```

result type :
```
const result: {
    someData: any;
}
```

result2 type :
```
const result: {
    someData: {value: string: disabled: boolean}[];
}
```

Overall `R.map(callback)(data)` doesn't infer the type of the `data` but `R.map(data, callback)` does

**Comment by cjquines** [comment]
this is a limitation of typescript; i don't think there's anything we can do here. there's no way for data-last `map` to infer the type. the `(data) => R.map(data, ...)` is a fine enough workaround i think?

**Comment by eranhirsch** [comment]
Possibly the `NoInfer` utility type might help in the future, but it'll take a while before we drop support for typescript versions below 5.4
