### ISSUE TITLE
`debounce` does not call on trailing edge in "leaky bucket" case

### ISSUE THREAD

**Issue by filipw01** [remeda/remeda#822]
I noticed there's already a debounce function (which I think in lodash can be used to simulate throttle) but it seems that remeda has a different behavior for the maxWait

See how I was able to get the throttle behavior of lodash using debounce https://stackblitz.com/edit/vitejs-vite-egpikb?file=src%2Fmain.ts

What do you think about adding equivalent of [docs-lodash.com/v4/throttle](https://docs-lodash.com/v4/throttle/) or changing debounce to closer align with the one in lodash (so that we could replicate throttle behavior)?

**Comment by eranhirsch** [comment]
Hey, I don't remember the specifics when I added debounce, but I *think* I made it compatible with the lodash impl, can you say in what way doesn't it work to implement throttle the same way lodash's debounce can be used to implement it?

**Comment by filipw01** [comment]
Did you take a look at the stackblitz I shared? I was able to replicate throttle behavior with lodash debounce, but not remeda debounce. If there's a way to do it do you mind sharing it? We could add it to the list of equivalent functions for migration from lodash page
<img width="425" alt="Screenshot 2024-08-12 at 21 15 03" src="https://github.com/user-attachments/assets/fba7ddea-efed-4504-97a8-a19ebc89703d">

**Comment by cjquines** [comment]
oh, i see why. let's say our throttle time is 100 and we're calling the function every 90 ms. then:

* the function is called at times 90, 180, 270, 360, 450
* lodash invokes at times 90, 190, 360, 460
* remeda invokes at times 90, 280, 460

i think the remeda implementation is in fact bugged when `maxWaitMs` is set and `timing` is `"both"`

**Comment by aretrace** [comment]
@cjquines, @SirJayEarn had `throttle` equivalent behavior in a [roadmap](https://github.com/remeda/remeda/issues/37) some time ago, any timeline for when this might be resolved?

**Comment by eranhirsch** [comment]
This is my repro. It sheds more light on which invocations are being delayed and suppressed. I just started looking at it, so I don't have a suggestion yet.

https://codesandbox.io/p/sandbox/4yl925?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0l7ov550006356l2q2lfvkc%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0l7ov530002356lm5qftfay%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0l7ov540003356lczr9221d%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0l7ov540005356l2qq5t5sv%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0l7ov530002356lm5qftfay%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0l7ov530001356lsnryzoho%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cm0l7ov530002356lm5qftfay%2522%252C%2522activeTabId%2522%253A%2522cm0l7ov530001356lsnryzoho%2522%257D%252C%2522cm0l7ov540005356l2qq5t5sv%2522%253A%257B%2522id%2522%253A%2522cm0l7ov540005356l2qq5t5sv%2522%252C%2522activeTabId%2522%253A%2522cm0l84xvy0066356l77kff57z%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0l7ov540004356lpo6hh06i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm0l7qbft001j356la3qz0gxm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm0l84xvy0066356l77kff57z%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0l7ov540003356lczr9221d%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0l7ov540003356lczr9221d%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by eranhirsch** [comment]
The bottom line is that for an interval of 900ms, throttle of 1000ms, (and 10 invocations) each function fires at these times:
Lodash: 0, 1000,       2700, 3700, 5400,       6400,       8100
Remeda: 0,       1900,       3700,       5500,       7300,      9100

**Comment by eranhirsch** [comment]
Visualized...

![output](https://github.com/user-attachments/assets/06d2d3b4-88ad-432e-b7fa-9789863c976d)
