### ISSUE TITLE
`toCamelCase` function producing unexpected output?

### ISSUE THREAD

**Issue by serkfi** [remeda/remeda#829]
It appears that the `toCamelCase` function may not be converting certain strings as expected. Below is an example that demonstrates this potential issue:

```
R.toCamelCase('aa-bb-cC_DEF_Gh Ijk'); 
// Current Output: 'aaBbCCDEFGhIjk'
// Expected Output: 'aaBbCcDefGhIjk'
```

I would expect the output to be `'aaBbCcDefGhIjk'`, where each new word is properly converted to camel case. However, in the current behavior, some uppercase characters are retained unexpectedly.

### Other Examples:
The following cases also seem to behave differently compared to the lodash implementation:

```
R.toCamelCase('FOO_FOO_FOO24');
// Output: 'fooFooFoo24'   // This is OK
```
However, the result in the case below seems incorrect:

```
R.toCamelCase('staticFOO_FOO_FOO24');
// Current Output: 'staticFOOFOOFOO24'
// Expected Output: 'staticFooFooFoo24'
```

It seems like there's inconsistency in how strings are being transformed, especially with certain patterns like multiple uppercase letters and underscores. Is this the intended behavior, or a bug? Would love to hear your thoughts on this.

**Comment by eranhirsch** [comment]
Hey, unfortunately, there is no single canonical definition for camel-casing a string. We chose to mirror the type-fest definition to use that type for the return. You can see in this playground that we follow the type-fest types:

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYQIYgKYBs0GcNwC+cAZlBCHAEQwCeYGAtCRrjFQNwBQXdDcAQQCMcALwp02PBgA8VVKkYAjJYwDGyAPoARAKIAxTQHEAFnACSAKwDWVADSI4YKKwxQAbhmQQAdvjUArjDAngCqYAxQaqj4AFxwMFABBIQAfNwA9BlwOQB6APy89AQCAExiEpg4MbLyiirqWnqGphY29o7Orh5evv5BIRjhkdFxpKhY+ETpXFk5cAU8fAQAQiLiaFXScmyowWr6APKHmkcnZ6UALB1IXfg93n4YgcFhEW6jGPGJydOZ2XlCkV+CtyhtJNV8DsYHtgAdjqcERdrg5bi57p5Hv1XkN3lEavESBMpml-vNFkA


Notice that toCamelCase supports an optional "options" object, allowing you to turn *off* the `preserveConsecutiveUppercase` option. When disabled, your second example is computed, matching your expected result.

**Comment by eranhirsch** [comment]
I just noticed that the options object is not documented at all.

**Comment by eranhirsch** [comment]
Even the lodash implementation doesn't return the result you expect in your first example:

```ts
_.camelCase("aa-bb-cC_DEF_Gh Ijk"); // "aaBbCCDefGhIjk"
```

**Comment by serkfi** [comment]
At least we found out that the documentation was lacking a bit. That option is actually what we were looking for to have.

Thanks for the answer!
