### ISSUE TITLE
Regex lookbehinds used in `toCamelCase` not supported in Safari < 16

### ISSUE THREAD

**Issue by jmheik** [remeda/remeda#833]
Regexes here https://github.com/remeda/remeda/blob/9d742036f6c9cdc216e2c771805051855e7e7ac4/src/internal/splitWords.ts#L36C7-L36C24 use lookbehinds which are not supported in Safari < 16 (https://caniuse.com/js-regexp-lookbehind). Should those versions still be supported?

**Comment by eranhirsch** [comment]
From the caniuse page lookbehinds were added to Safari 16.4, and that version has been superseded by v17 for over a year and is no longer supported by Apple.

We maintain backwards compatibility with Node versions which are *still supported*, and don't do any validation for support for browser versions.
