### ISSUE TITLE
flatMap should not accept functions that don't return an array

### ISSUE THREAD

**Issue by jbpotonnier** [remeda/remeda#84]
The following tests is succeeding. 

```ts
 const actual = flatMap([1, 2] as const, x => x * 2);
 expect(actual).toEqual([2, 4])
```
In a typed context, I woudn't expect it to even typecheck.

I see that the accepted function type is  `fn: (input: T) => K | K[]`
Why not ` fn: (input: T) => K[]`

Maybe there is a good reason I fail to see ?

**Comment by lstkz** [comment]
Lodash and Ramda work in the same way.

```js
import * as R from 'ramda';
import * as _ from 'lodash';

console.log(R.chain((x) => (x % 2 ? x : [x, x]), [1, 2, 3])); // => [ 1, 2, 2, 3 ]
console.log(_.flatMap([1, 2, 3], (x) => (x % 2 ? x : [x, x]))); // => [ 1, 2, 2, 3 ]
```
