### ISSUE TITLE
`clone` doesn't work with `dayjs` package

### ISSUE THREAD

**Issue by ArturBaybulatov** [remeda/remeda#857]
```ts
const date = dayjs()
console.log(date.format('YYYY-MM-DD'))
// OK

const clonedDate = clone(date)
console.log(clonedDate.format('YYYY-MM-DD'))
// Uncaught TypeError: clonedDate.format is not a function
```

**Comment by cjquines** [comment]
oh, it looks like the supported types doc disappeared

> Supported types: `Array`, `Object`, `Number`, `String`, `Boolean`, `Date`, `RegExp`.

**Comment by cjquines** [comment]
in particular you should use the [dayjs clone](https://day.js.org/docs/en/parse/dayjs-clone)

**Comment by ArturBaybulatov** [comment]
I know about `dayjs().clone()`, but it's not that convenient when cloning large nested structures containing fields with such dates. Thanks anyway!
