### ISSUE TITLE
`isString` not narrowing type

### ISSUE THREAD

**Issue by bombillazo** [remeda/remeda#862]
Hey, we've been using `isString` to do some type narrowing but recently TS is not narrowing the type for the passed object
![image](https://github.com/user-attachments/assets/a6cb6255-03ef-44e4-af1e-d26985132802)

**Comment by eranhirsch** [comment]
Can you share a more comprehensive example? Prefer to use the typescript playground or codesandbox so that we can have a full repro

**Comment by bombillazo** [comment]
Seems this was a fluke issue caused by some uncached deps in our local dev env. After cleaning our node_modules and resintalling, it;s working. Closing .

**Comment by eranhirsch** [comment]
I am marking as invalid so we can track non-issue issues.
