### ISSUE TITLE
Netlify open source requirements 

### ISSUE THREAD

**Issue by lstkz** [remeda/remeda#875]
Currently, we are using a free Netlify account, and we are slowly reaching the limit. It's possible to apply for open-source account.
We need to meet the following requirements:
- Code of Conduct 
- Netlify link on the page is required.
Source https://www.netlify.com/legal/open-source-policy/

Can someone add it quickly?

**Comment by eranhirsch** [comment]
I'm on it, i just haven't had time recently to handle it. We might need to spin up an email domain on remedajs.com for the code of conduct.

**Comment by lstkz** [comment]
Custom emails cost money. Something like ~10$/month. We can use my private email.
ChatGPT generated Code of conduct should be enough I think. https://chatgpt.com/share/66fe7385-234c-8005-8a40-4a982826d01e
