### ISSUE TITLE
Using clone for DOMRect object will return a empty object

### ISSUE THREAD

**Issue by YangPengYao** [remeda/remeda#876]
code: 
<img width="459" alt="截圖 2024-10-05 下午4 54 51" src="https://github.com/user-attachments/assets/be5d341e-393c-49f2-9efc-f5dd013343b9">

browser console:
<img width="378" alt="截圖 2024-10-05 下午4 52 29" src="https://github.com/user-attachments/assets/b50ad147-95ef-431f-8eae-402130572f54">

**Comment by cjquines** [comment]
the clone function explicitly says which types are permitted. i'm not sure whether we can enforce this on the type level (perhaps instanceof)

**Comment by YangPengYao** [comment]
Thank you for your replication ~
