### ISSUE TITLE
Replacement for Lodash `countBy`

### ISSUE THREAD

**Issue by cjquines** [remeda/remeda#885]
Right now `countBy(data, fn)` is the composition `mapValues(groupBy(data, fn), length())`, which is a bit unwieldy.

* Lodash and Ramda have `countBy`.
* Python has `collections.Counter`, which is `countBy(data, identity())`, and is what I use most often by far.
* Hack has `Dict\count_values`, which is also `countBy(data, identity())`.
* The Rust crate [`counter`](https://crates.io/crates/counter) is quite popular (21k weekly downloads), and it is also `countBy(data, identity())`.

**Comment by eranhirsch** [comment]
The composed solution is also less efficient as it requires building the whole array just to get the count so there's a perf advantage too.

Interestingly, the most abstract/generic/general-purpose function that would cover all cases would be a groupBy-adjacent function that accepts a second reducer callback:

```ts
function reduceBy<T, K extends PropertyKey, V>(
  data: ReadonlyArray<T>,
  grouper: (item: T) => K,
  reducer: (accumulator: V, item: T) => V,
  initialValue: V,
): Record<K, V>;
```

**Comment by cjquines** [comment]
i agree that's the most general solution, but that's such a horrifying signature that i'm not sure i want it
