### ISSUE TITLE
Unsafe type inference with `pick`

### ISSUE THREAD

**Issue by radekn** [remeda/remeda#886]
When the result of `pick` is fed directly to `mapValues`, it unnecessarily widens `pick`'s key type, which reduces type safety:
```ts
const o = {
  foo: "hello",
  bar: "world",
};

const asdf = mapValues(pick(o, ["foo"]), (x) => x);
// 'bar' is not there, but no error - not good!
asdf.bar satisfies string;
```
[TS Playground link](https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&jsx=0&ts=5.6.3#code/JYWwDg9gTgLgBAbzmYBjA1gGjiAhmANVwBsBXAUwGc4BfOAMyghDgCIpyRyATXVgbgCwAKBGoIAO0rwIcALyIRcBhAgAuNgAtyxYhFaYlcAEa4oG1gHdoxbgZE0ho4QHoXcACrbkTY8U5qIghGbp4AnmDkcMAS9OQcEqhRlsDc5BI8cAAGKBhZAOTUWQDSWXAwslno5GEQ9J5ZRuJS8LiU3PUKeIQkFJQAFLno-RDYANqs9KqsALoAlNj9AB5z8gB8cCtOyqHKcAB6APwh7vmmUPnR1BIQ8DDaHNjGpPA3cPFMUHAAtHA38ABzVTcACEJzgAAEYJRvuQlpFUDBYVBPnAAApMSKwMJwM5mS7cCBUP63d5LYDSOCScoRKL5JBTdRwaRQGIA-i0fJGNodAB052ZuBgFPowGJLLZThoIhEoQA6tB0GYIKQJNxAsJgsJlM1KTzOjh8EQyFRBmhhqM4BNGbM4G04LqYAs4MtVnINltwXsjuCoTC4QikR9oOjMfEYDi8Rc4ITif8yRSZBIaZFcQzVBoJRJ2Zzue16PyzILhZRReKYKzs1KZa53ABlCBkYXU-pTL4eWl11CssDwACsvJWGv64K8UUkxBx3GA9DiCSSV2yjrKxnIbaixSMQw0AB4PGSYOluNQIMYAFbkRHYR1wYoHo-Uaq1eoeNYj7V7U8XxEaDyGD-KBIuBcJQGgAErkLghISJOACCKK4GEO7FGs-7KG6Gxouae7YCh-4YYoH43vq8iGj0JoDEMIzjJM0zzIsKzrJsczbHAuzKD6H6hH6sLwpeQYoiGGIQFiEa4ucBJEtcpJwomVLJhGqb0ioTJZjmNBch++qFl8lBCiKYrUGpUpOEAA)

Adding `as const` prevents type inference from widening the type, but the downside is you have to remember to use it everywhere:
```ts
const asdf = mapValues(pick(o, ["foo"] as const), (x) => x);
```

If you're not planning to support TypeScript 4.x, adding a [const modifiers](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters) to `K` in `pick`'s signature might be a good idea - it would improve type safety by making the above workaround unnecessary. What do you think?

**Comment by cjquines** [comment]
our min ts version for remeda 2 is ts 5.1, so we can def put a `const` there. i think we can do the same thing with other functions like `constant`
