### ISSUE TITLE
docs: `identity` and `doNothing` are missing in document site

### ISSUE THREAD

**Issue by aleung** [remeda/remeda#887]
They are linked in `constant` and the links are broken.

>  See also: [doNothing](https://remedajs.com/docs/#doNothing) - A function that doesn't return anything. [identity](https://remedajs.com/docs/#identity) - A function that returns the first argument it receives.

![image](https://github.com/user-attachments/assets/2d0b2542-d4bd-43a6-85e8-d8b091c86d41)

**Comment by eranhirsch** [comment]
Thanks for reporting.
