### ISSUE TITLE
Why ReturnType here ?

### ISSUE THREAD

**Issue by olsonpm** [remeda/remeda#894]
In [commit b1d6370](https://github.com/remeda/remeda/commit/b1d63708e134007ed3260e1f5d85ba742c32e88c) `Feature/reverse for tuples`, the following code is introduced.

```ts
type Reverse<
  T extends readonly unknown[],
  R extends readonly unknown[] = []
> = ReturnType< // <----------------- why ReturnType here ?
  T extends IsNoTuple<T>
    ? () => [...T, ...R]
    : T extends readonly [infer F, ...infer L]
    ? () => Reverse<L, [F, ...R]>
    : () => R
>;
```

I was hoping someone could explain the usage of ReturnType here as I would expect the type to be

```ts
type Reverse<
  T extends ReadonlyArray<unknown>,
  R extends ReadonlyArray<unknown> = []
> =
  T extends IsNoTuple<T>
    ? [...T, ...R]
    : T extends readonly [infer F, ...infer L]
      ? Reverse<L, [F, ...R]>
      : R
```

I assume there's some typescript behavior being manipulated - and was hoping y'all could mention what it is.

**Comment by eranhirsch** [comment]
This code predates my time working on the library. If you have an issue caused by this you can share more info on that and I'll try to help, otherwise, if you are just curious you can try to ping the pr #95 to ask the author directly.

**Comment by olsonpm** [comment]
Thanks eran - will do.
