### ISSUE TITLE
[doc] Doc url's are broken.

### ISSUE THREAD

**Issue by estaub** [remeda/remeda#9]
The url https://remedajs.com/docs doesn't work, nor (of course) does any hashmark off it, e.g. https://remedajs.com/docs#addProp .  This means that back-arrow in the browser is broken, and bookmarking is impossible.

I haven't kicked the tires on rameda yet, but I'm very much aligned with your priorities - glad to see someone's doing this!

**Comment by BetterCallSky** [comment]
thanks for reporting it @estaub!
It's fixed now
