### ISSUE TITLE
Add partition

### ISSUE THREAD

**Issue by maxfi** [remeda/remeda#96]
This would be a small but useful addition. It could perhaps be based on https://gist.github.com/zachlysobey/71ac85046d0d533287ed85e1caa64660.

**Comment by maxfi** [comment]
If I create a PR would it be accepted? Thanks. 🙏

**Comment by santialbo** [comment]
I'd be interested in this! Please open a PR

**Comment by maxfi** [comment]
I'm considering switching to https://github.com/digimuza/ts-prime which already has a [`partition` function](https://digimuza.github.io/ts-prime/#/documentation/partition).

**Comment by TkDodo** [comment]
Hi, I think you can open a PR with the partition function. we can also merge the implementation from `ts-prime` back to `remeda`. Not sure how far ahead ts-prime is, but we can certainly think about merging those two if the goals are aligned.

**Comment by maxfi** [comment]
Thanks for the feedback @TkDodo. 🙏 Would it be possible to check with @digimuza if it's possible to merge some upstream functionality? As far as I'm aware it's all tree shakable so maybe won't be an issue for remeda? 🤷‍♂️

**Comment by TkDodo** [comment]
> As far as I'm aware it's all tree shakable so maybe won't be an issue for remeda?

I understand that as well. It depends if any breaking changes have been made since. maybe @digimuza can comment on that, and I'd also  obviously would want @lstkz approval for this move.

That being said, my first task would be to get the `guards` PR (https://github.com/remeda/remeda/pull/67) merged, I think it's a good addition.

**Comment by dartess** [comment]
https://github.com/remeda/remeda/pull/169 it seems the issue can be closed @TkDodo
